import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const companies = [
  {
    name: "Comcast/Xfinity",
    slug: "comcast-xfinity",
    category: "Internet",
    avgMonthlyPrice: 89.99,
    difficultyScore: 5.0,
    darkPatternScore: 8.5,
    cancellationUrl: null,
    cancellationPhone: "1-800-934-6489",
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Call 1-800-934-6489 (Xfinity customer service)" },
      { step: 2, instruction: "Navigate through the automated menu — say 'Cancel Service' or press 0 for an agent" },
      { step: 3, instruction: "Be prepared for a long hold time (15-45 minutes typical)" },
      { step: 4, instruction: "The retention specialist will offer discounts — stay firm if you want to cancel" },
      { step: 5, instruction: "Request a confirmation number and email confirmation" },
      { step: 6, instruction: "Return all equipment to an Xfinity store to avoid equipment fees" },
    ],
  },
  {
    name: "Planet Fitness",
    slug: "planet-fitness",
    category: "Fitness",
    avgMonthlyPrice: 24.99,
    difficultyScore: 4.8,
    darkPatternScore: 7.5,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "You MUST cancel in person at your home club or via certified mail" },
      { step: 2, instruction: "Online cancellation is NOT available" },
      { step: 3, instruction: "Visit your home club and ask the front desk for a cancellation form" },
      { step: 4, instruction: "Fill out the form and get a copy for your records" },
      { step: 5, instruction: "Alternative: Send a certified letter to your home club requesting cancellation" },
      { step: 6, instruction: "Note: There may be a $58 buyout fee if you cancel before 12 months" },
    ],
  },
  {
    name: "Adobe Creative Cloud",
    slug: "adobe-creative-cloud",
    category: "Design",
    avgMonthlyPrice: 54.99,
    difficultyScore: 4.5,
    darkPatternScore: 8.0,
    cancellationUrl: "https://account.adobe.com/plans",
    cancellationPhone: "1-800-833-6687",
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to account.adobe.com/plans" },
      { step: 2, instruction: "Click 'Manage plan' next to your subscription" },
      { step: 3, instruction: "Click 'Cancel plan'" },
      { step: 4, instruction: "Adobe will show an early termination fee (50% of remaining months) — negotiate!" },
      { step: 5, instruction: "Go through multiple retention screens with discount offers" },
      { step: 6, instruction: "Confirm cancellation and save your confirmation email" },
    ],
  },
  {
    name: "Adobe Acrobat",
    slug: "adobe-acrobat",
    category: "Productivity",
    avgMonthlyPrice: 19.99,
    difficultyScore: 4.7,
    darkPatternScore: 8.0,
    cancellationUrl: "https://account.adobe.com/plans",
    cancellationPhone: "1-800-833-6687",
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to account.adobe.com/plans" },
      { step: 2, instruction: "Click 'Manage plan' for Acrobat" },
      { step: 3, instruction: "Click 'Cancel plan' — expect early termination fee warnings" },
      { step: 4, instruction: "Navigate through 4-5 retention offer screens" },
      { step: 5, instruction: "Confirm cancellation" },
    ],
  },
  {
    name: "McAfee Antivirus",
    slug: "mcafee-antivirus",
    category: "Security",
    avgMonthlyPrice: 8.33,
    difficultyScore: 4.5,
    darkPatternScore: 9.0,
    cancellationUrl: "https://home.mcafee.com/root/myaccount.aspx",
    cancellationPhone: "1-866-622-3911",
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Log in to home.mcafee.com" },
      { step: 2, instruction: "Go to My Account > Subscriptions" },
      { step: 3, instruction: "Turn off Auto-Renewal" },
      { step: 4, instruction: "Navigate through multiple scare tactics warning about 'unprotected device'" },
      { step: 5, instruction: "Confirm cancellation despite pop-ups" },
      { step: 6, instruction: "Check email — they may still charge. Call 1-866-622-3911 if needed" },
    ],
  },
  {
    name: "Norton Antivirus",
    slug: "norton-antivirus",
    category: "Security",
    avgMonthlyPrice: 7.49,
    difficultyScore: 4.3,
    darkPatternScore: 8.5,
    cancellationUrl: "https://manage.norton.com",
    cancellationPhone: "1-844-488-4540",
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Sign in at manage.norton.com" },
      { step: 2, instruction: "Click on your subscription" },
      { step: 3, instruction: "Turn off 'Auto-Renew'" },
      { step: 4, instruction: "Navigate through multiple retention/scare screens" },
      { step: 5, instruction: "Confirm cancellation" },
    ],
  },
  {
    name: "Gold's Gym",
    slug: "golds-gym",
    category: "Fitness",
    avgMonthlyPrice: 34.99,
    difficultyScore: 4.2,
    darkPatternScore: 6.5,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Visit your home gym in person" },
      { step: 2, instruction: "Ask for a cancellation form at the front desk" },
      { step: 3, instruction: "Some locations require 30 days written notice" },
      { step: 4, instruction: "Alternative: Send a certified letter to your home gym" },
      { step: 5, instruction: "Follow up to confirm cancellation processed" },
    ],
  },
  {
    name: "NYT Digital",
    slug: "nyt-digital",
    category: "News",
    avgMonthlyPrice: 17.00,
    difficultyScore: 4.0,
    darkPatternScore: 6.0,
    cancellationUrl: null,
    cancellationPhone: "1-800-591-9233",
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "You must call 1-800-591-9233 to cancel (no online option for most plans)" },
      { step: 2, instruction: "Chat support may also work — try live chat first" },
      { step: 3, instruction: "Be prepared for strong retention offers" },
      { step: 4, instruction: "Stay firm and request cancellation confirmation" },
    ],
  },
  {
    name: "WSJ Digital",
    slug: "wsj-digital",
    category: "News",
    avgMonthlyPrice: 38.99,
    difficultyScore: 4.0,
    darkPatternScore: 5.5,
    cancellationUrl: null,
    cancellationPhone: "1-800-568-7625",
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Call 1-800-568-7625" },
      { step: 2, instruction: "Request cancellation from the agent" },
      { step: 3, instruction: "Decline retention offers if you want to fully cancel" },
      { step: 4, instruction: "Get confirmation number" },
    ],
  },
  {
    name: "Audible",
    slug: "audible",
    category: "Entertainment",
    avgMonthlyPrice: 14.95,
    difficultyScore: 3.5,
    darkPatternScore: 5.0,
    cancellationUrl: "https://www.audible.com/account/cancel",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to audible.com/account" },
      { step: 2, instruction: "Click 'Cancel membership' at the bottom" },
      { step: 3, instruction: "Navigate through 3-4 retention offer screens" },
      { step: 4, instruction: "They may offer a pause or discounted rate — decide if worth it" },
      { step: 5, instruction: "Confirm cancellation. Your credits remain until used" },
    ],
  },
  {
    name: "Amazon Prime",
    slug: "amazon-prime",
    category: "Shopping",
    avgMonthlyPrice: 14.99,
    difficultyScore: 2.8,
    darkPatternScore: 6.0,
    cancellationUrl: "https://www.amazon.com/mc/pipelines/cancel-prime",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to amazon.com > Account > Prime Membership" },
      { step: 2, instruction: "Click 'End Membership'" },
      { step: 3, instruction: "Navigate through reminder screens about benefits you'll lose" },
      { step: 4, instruction: "Choose end date (immediate or end of billing period)" },
      { step: 5, instruction: "Confirm cancellation" },
    ],
  },
  {
    name: "Microsoft 365",
    slug: "microsoft-365",
    category: "Productivity",
    avgMonthlyPrice: 9.99,
    difficultyScore: 2.5,
    darkPatternScore: 4.0,
    cancellationUrl: "https://account.microsoft.com/services",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to account.microsoft.com/services" },
      { step: 2, instruction: "Find Microsoft 365 subscription" },
      { step: 3, instruction: "Click 'Manage' then 'Cancel subscription'" },
      { step: 4, instruction: "Follow the prompts to confirm" },
    ],
  },
  {
    name: "LinkedIn Premium",
    slug: "linkedin-premium",
    category: "Professional",
    avgMonthlyPrice: 29.99,
    difficultyScore: 2.5,
    darkPatternScore: 4.5,
    cancellationUrl: "https://www.linkedin.com/psettings/cancel-premium",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to linkedin.com > Settings > Manage Premium account" },
      { step: 2, instruction: "Click 'Cancel subscription'" },
      { step: 3, instruction: "Navigate through retention screens" },
      { step: 4, instruction: "Confirm cancellation" },
    ],
  },
  {
    name: "Slack",
    slug: "slack",
    category: "Productivity",
    avgMonthlyPrice: 8.75,
    difficultyScore: 2.2,
    darkPatternScore: 2.0,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Only workspace owners/admins can change billing" },
      { step: 2, instruction: "Go to Settings & Administration > Billing" },
      { step: 3, instruction: "Click 'Change plan type' and select Free" },
      { step: 4, instruction: "Confirm downgrade" },
    ],
  },
  {
    name: "Grammarly",
    slug: "grammarly",
    category: "Productivity",
    avgMonthlyPrice: 12.00,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    cancellationUrl: "https://account.grammarly.com/subscription",
    cancellationPhone: null,
    cancellationEmail: "support@grammarly.com",
    cancellationSteps: [
      { step: 1, instruction: "Log in to account.grammarly.com" },
      { step: 2, instruction: "Go to Subscription" },
      { step: 3, instruction: "Click 'Cancel subscription'" },
      { step: 4, instruction: "Confirm via the prompts" },
    ],
  },
  {
    name: "Hulu",
    slug: "hulu",
    category: "Streaming",
    avgMonthlyPrice: 17.99,
    difficultyScore: 1.8,
    darkPatternScore: 3.0,
    cancellationUrl: "https://secure.hulu.com/account",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to secure.hulu.com/account" },
      { step: 2, instruction: "Click 'Cancel' under Your Subscription" },
      { step: 3, instruction: "Select a reason and confirm" },
    ],
  },
  {
    name: "Canva Pro",
    slug: "canva-pro",
    category: "Design",
    avgMonthlyPrice: 12.99,
    difficultyScore: 1.8,
    darkPatternScore: 2.5,
    cancellationUrl: "https://www.canva.com/settings/billing",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to canva.com > Settings > Billing & plans" },
      { step: 2, instruction: "Click 'Cancel subscription'" },
      { step: 3, instruction: "Confirm cancellation" },
    ],
  },
  {
    name: "Netflix",
    slug: "netflix",
    category: "Streaming",
    avgMonthlyPrice: 15.49,
    difficultyScore: 1.5,
    darkPatternScore: 1.5,
    cancellationUrl: "https://www.netflix.com/cancelplan",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to netflix.com/cancelplan or Account > Cancel Membership" },
      { step: 2, instruction: "Click 'Finish Cancellation'" },
      { step: 3, instruction: "Your account stays active until the end of the billing period" },
    ],
  },
  {
    name: "HBO Max",
    slug: "hbo-max",
    category: "Streaming",
    avgMonthlyPrice: 15.99,
    difficultyScore: 1.5,
    darkPatternScore: 2.0,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Open the Max app or go to max.com" },
      { step: 2, instruction: "Go to Settings > Subscription" },
      { step: 3, instruction: "Select 'Cancel Subscription'" },
      { step: 4, instruction: "Note: If subscribed through Apple/Google, cancel through their stores" },
    ],
  },
  {
    name: "YouTube Premium",
    slug: "youtube-premium",
    category: "Streaming",
    avgMonthlyPrice: 13.99,
    difficultyScore: 1.5,
    darkPatternScore: 2.0,
    cancellationUrl: "https://www.youtube.com/paid_memberships",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to youtube.com/paid_memberships" },
      { step: 2, instruction: "Click 'Manage membership'" },
      { step: 3, instruction: "Click 'Deactivate' or 'Cancel'" },
      { step: 4, instruction: "Confirm" },
    ],
  },
  {
    name: "Spotify",
    slug: "spotify",
    category: "Music",
    avgMonthlyPrice: 10.99,
    difficultyScore: 1.2,
    darkPatternScore: 1.0,
    cancellationUrl: "https://www.spotify.com/account/subscription",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to spotify.com/account/subscription" },
      { step: 2, instruction: "Click 'Change plan'" },
      { step: 3, instruction: "Select 'Cancel Premium'" },
      { step: 4, instruction: "Confirm. You'll keep Premium until end of billing period" },
    ],
  },
  {
    name: "Disney+",
    slug: "disney-plus",
    category: "Streaming",
    avgMonthlyPrice: 13.99,
    difficultyScore: 1.3,
    darkPatternScore: 1.5,
    cancellationUrl: "https://www.disneyplus.com/account",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to disneyplus.com/account" },
      { step: 2, instruction: "Click your subscription" },
      { step: 3, instruction: "Select 'Cancel Subscription'" },
      { step: 4, instruction: "Confirm" },
    ],
  },
  {
    name: "Peacock",
    slug: "peacock",
    category: "Streaming",
    avgMonthlyPrice: 7.99,
    difficultyScore: 1.5,
    darkPatternScore: 2.0,
    cancellationUrl: "https://www.peacocktv.com/account/plans",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to peacocktv.com/account" },
      { step: 2, instruction: "Click 'Plans & Payment'" },
      { step: 3, instruction: "Select 'Cancel Plan'" },
      { step: 4, instruction: "Confirm cancellation" },
    ],
  },
  {
    name: "Paramount+",
    slug: "paramount-plus",
    category: "Streaming",
    avgMonthlyPrice: 11.99,
    difficultyScore: 1.5,
    darkPatternScore: 2.0,
    cancellationUrl: "https://www.paramountplus.com/account",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to paramountplus.com/account" },
      { step: 2, instruction: "Click 'Cancel Subscription'" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "Apple TV+",
    slug: "apple-tv-plus",
    category: "Streaming",
    avgMonthlyPrice: 9.99,
    difficultyScore: 1.5,
    darkPatternScore: 1.5,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "On iPhone: Settings > Apple ID > Subscriptions" },
      { step: 2, instruction: "Find Apple TV+ and tap 'Cancel'" },
      { step: 3, instruction: "On web: tv.apple.com > Account > Manage Subscriptions" },
    ],
  },
  {
    name: "Apple Music",
    slug: "apple-music",
    category: "Music",
    avgMonthlyPrice: 10.99,
    difficultyScore: 1.5,
    darkPatternScore: 1.5,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "On iPhone: Settings > Apple ID > Subscriptions" },
      { step: 2, instruction: "Find Apple Music and tap 'Cancel'" },
      { step: 3, instruction: "On Mac: App Store > Account > Subscriptions" },
    ],
  },
  {
    name: "Tidal",
    slug: "tidal",
    category: "Music",
    avgMonthlyPrice: 10.99,
    difficultyScore: 1.5,
    darkPatternScore: 2.0,
    cancellationUrl: "https://account.tidal.com/subscription",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to account.tidal.com" },
      { step: 2, instruction: "Click on Subscription" },
      { step: 3, instruction: "Select 'Cancel subscription'" },
    ],
  },
  {
    name: "Dropbox",
    slug: "dropbox",
    category: "Cloud Storage",
    avgMonthlyPrice: 11.99,
    difficultyScore: 2.5,
    darkPatternScore: 4.0,
    cancellationUrl: "https://www.dropbox.com/account/plan",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to dropbox.com > Settings > Plan" },
      { step: 2, instruction: "Click 'Cancel plan' or 'Downgrade'" },
      { step: 3, instruction: "Navigate through retention screens" },
      { step: 4, instruction: "Confirm downgrade to Basic (free)" },
    ],
  },
  {
    name: "Zoom",
    slug: "zoom",
    category: "Productivity",
    avgMonthlyPrice: 13.33,
    difficultyScore: 2.0,
    darkPatternScore: 2.5,
    cancellationUrl: "https://zoom.us/account/billing",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Sign in to zoom.us" },
      { step: 2, instruction: "Go to Admin > Account Management > Billing" },
      { step: 3, instruction: "Click 'Cancel subscription'" },
      { step: 4, instruction: "Confirm" },
    ],
  },
  {
    name: "NordVPN",
    slug: "nordvpn",
    category: "Security",
    avgMonthlyPrice: 12.99,
    difficultyScore: 3.0,
    darkPatternScore: 5.0,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: "support@nordvpn.com",
    cancellationSteps: [
      { step: 1, instruction: "Log in to my.nordaccount.com" },
      { step: 2, instruction: "Go to Subscription > Change plan" },
      { step: 3, instruction: "Select 'Cancel automatic payments'" },
      { step: 4, instruction: "For refund: Contact support via live chat within 30 days" },
    ],
  },
  {
    name: "ExpressVPN",
    slug: "expressvpn",
    category: "Security",
    avgMonthlyPrice: 12.95,
    difficultyScore: 2.5,
    darkPatternScore: 3.5,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: "support@expressvpn.com",
    cancellationSteps: [
      { step: 1, instruction: "Log in to your ExpressVPN account" },
      { step: 2, instruction: "Go to Subscription settings" },
      { step: 3, instruction: "Turn off auto-renewal" },
      { step: 4, instruction: "For refund: Contact live chat within 30 days" },
    ],
  },
  {
    name: "Notion",
    slug: "notion",
    category: "Productivity",
    avgMonthlyPrice: 10.00,
    difficultyScore: 1.5,
    darkPatternScore: 1.5,
    cancellationUrl: "https://www.notion.so/settings",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to notion.so > Settings > Billing" },
      { step: 2, instruction: "Click 'Downgrade' to free plan" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "Figma",
    slug: "figma",
    category: "Design",
    avgMonthlyPrice: 15.00,
    difficultyScore: 1.8,
    darkPatternScore: 2.0,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: "support@figma.com",
    cancellationSteps: [
      { step: 1, instruction: "Go to figma.com > Account settings > Billing" },
      { step: 2, instruction: "Click 'Downgrade to Starter'" },
      { step: 3, instruction: "Confirm downgrade" },
    ],
  },
  {
    name: "Evernote",
    slug: "evernote",
    category: "Productivity",
    avgMonthlyPrice: 14.99,
    difficultyScore: 2.8,
    darkPatternScore: 4.5,
    cancellationUrl: "https://www.evernote.com/Settings.action",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to evernote.com > Account Settings > Billing" },
      { step: 2, instruction: "Select 'Downgrade to Basic'" },
      { step: 3, instruction: "Navigate through retention screens" },
      { step: 4, instruction: "Confirm downgrade" },
    ],
  },
  {
    name: "Headspace",
    slug: "headspace",
    category: "Health",
    avgMonthlyPrice: 12.99,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: "help@headspace.com",
    cancellationSteps: [
      { step: 1, instruction: "Open the Headspace app" },
      { step: 2, instruction: "Go to Settings > Manage Subscription" },
      { step: 3, instruction: "Cancel through your app store (Apple/Google)" },
    ],
  },
  {
    name: "Calm",
    slug: "calm",
    category: "Health",
    avgMonthlyPrice: 14.99,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: "help@calm.com",
    cancellationSteps: [
      { step: 1, instruction: "Cancel through your app store subscription management" },
      { step: 2, instruction: "iPhone: Settings > Apple ID > Subscriptions > Calm" },
      { step: 3, instruction: "Android: Play Store > Payments & subscriptions > Calm" },
    ],
  },
  {
    name: "Duolingo Plus",
    slug: "duolingo-plus",
    category: "Education",
    avgMonthlyPrice: 12.99,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Cancel through your app store" },
      { step: 2, instruction: "iPhone: Settings > Apple ID > Subscriptions" },
      { step: 3, instruction: "Android: Play Store > Payments & subscriptions" },
      { step: 4, instruction: "Web: duolingo.com > Settings > Super Duolingo > Cancel" },
    ],
  },
  {
    name: "Peloton",
    slug: "peloton",
    category: "Fitness",
    avgMonthlyPrice: 44.00,
    difficultyScore: 3.0,
    darkPatternScore: 4.0,
    cancellationUrl: null,
    cancellationPhone: "1-866-679-9129",
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Log in to members.onepeloton.com" },
      { step: 2, instruction: "Go to My Membership" },
      { step: 3, instruction: "Click 'Cancel membership'" },
      { step: 4, instruction: "If you have a bike/tread, you may still need the app membership" },
    ],
  },
  {
    name: "SiriusXM",
    slug: "siriusxm",
    category: "Entertainment",
    avgMonthlyPrice: 16.99,
    difficultyScore: 4.0,
    darkPatternScore: 7.0,
    cancellationUrl: null,
    cancellationPhone: "1-866-635-2349",
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "You MUST call 1-866-635-2349 to cancel" },
      { step: 2, instruction: "Online cancellation is not available" },
      { step: 3, instruction: "Expect strong retention offers and long hold times" },
      { step: 4, instruction: "Stay firm and request cancellation confirmation" },
    ],
  },
  {
    name: "HelloFresh",
    slug: "hellofresh",
    category: "Food",
    avgMonthlyPrice: 51.93,
    difficultyScore: 3.5,
    darkPatternScore: 5.5,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Log in to hellofresh.com" },
      { step: 2, instruction: "Go to Account Settings > Plan Settings" },
      { step: 3, instruction: "Scroll down and click 'Cancel plan'" },
      { step: 4, instruction: "Navigate through 5+ retention screens" },
      { step: 5, instruction: "You may need to 'pause' first, then cancel" },
    ],
  },
  {
    name: "Blue Apron",
    slug: "blue-apron",
    category: "Food",
    avgMonthlyPrice: 47.95,
    difficultyScore: 3.0,
    darkPatternScore: 4.5,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Log in to blueapron.com" },
      { step: 2, instruction: "Go to Account > Plan & Delivery" },
      { step: 3, instruction: "Select 'Cancel plan'" },
      { step: 4, instruction: "Navigate retention screens and confirm" },
    ],
  },
  {
    name: "BetterHelp",
    slug: "betterhelp",
    category: "Health",
    avgMonthlyPrice: 65.00,
    difficultyScore: 3.0,
    darkPatternScore: 4.0,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: "contact@betterhelp.com",
    cancellationSteps: [
      { step: 1, instruction: "Log in to betterhelp.com" },
      { step: 2, instruction: "Go to Settings (gear icon)" },
      { step: 3, instruction: "Click 'Payment settings'" },
      { step: 4, instruction: "Select 'Cancel membership'" },
      { step: 5, instruction: "Navigate through retention offers" },
    ],
  },
  {
    name: "Coursera Plus",
    slug: "coursera-plus",
    category: "Education",
    avgMonthlyPrice: 59.00,
    difficultyScore: 2.5,
    darkPatternScore: 3.0,
    cancellationUrl: "https://www.coursera.org/my-purchases",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to coursera.org > My Purchases" },
      { step: 2, instruction: "Find your Coursera Plus subscription" },
      { step: 3, instruction: "Click 'Cancel' and follow prompts" },
    ],
  },
  {
    name: "MasterClass",
    slug: "masterclass",
    category: "Education",
    avgMonthlyPrice: 10.00,
    difficultyScore: 2.5,
    darkPatternScore: 3.5,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: "support@masterclass.com",
    cancellationSteps: [
      { step: 1, instruction: "Go to masterclass.com > Account Settings" },
      { step: 2, instruction: "Click 'Cancel Membership'" },
      { step: 3, instruction: "Navigate retention screens and confirm" },
    ],
  },
  {
    name: "Instacart+",
    slug: "instacart-plus",
    category: "Shopping",
    avgMonthlyPrice: 9.99,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Open Instacart app or website" },
      { step: 2, instruction: "Go to Account > Instacart+ Membership" },
      { step: 3, instruction: "Select 'Cancel membership'" },
      { step: 4, instruction: "Confirm" },
    ],
  },
  {
    name: "DoorDash DashPass",
    slug: "doordash-dashpass",
    category: "Food",
    avgMonthlyPrice: 9.99,
    difficultyScore: 1.8,
    darkPatternScore: 2.5,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Open DoorDash app" },
      { step: 2, instruction: "Go to Account > Manage DashPass" },
      { step: 3, instruction: "Select 'Cancel DashPass'" },
      { step: 4, instruction: "Confirm cancellation" },
    ],
  },
  {
    name: "Uber One",
    slug: "uber-one",
    category: "Transport",
    avgMonthlyPrice: 9.99,
    difficultyScore: 1.8,
    darkPatternScore: 2.5,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Open Uber app" },
      { step: 2, instruction: "Go to Account > Uber One" },
      { step: 3, instruction: "Select 'Manage membership'" },
      { step: 4, instruction: "Click 'End membership'" },
    ],
  },
  {
    name: "ChatGPT Plus",
    slug: "chatgpt-plus",
    category: "AI",
    avgMonthlyPrice: 20.00,
    difficultyScore: 1.5,
    darkPatternScore: 1.0,
    cancellationUrl: "https://chat.openai.com/#settings/BillingSettings",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to chat.openai.com > Settings > Subscription" },
      { step: 2, instruction: "Click 'Manage my subscription'" },
      { step: 3, instruction: "Select 'Cancel plan'" },
      { step: 4, instruction: "Confirm" },
    ],
  },
  {
    name: "GitHub Copilot",
    slug: "github-copilot",
    category: "AI",
    avgMonthlyPrice: 10.00,
    difficultyScore: 1.2,
    darkPatternScore: 0.5,
    cancellationUrl: "https://github.com/settings/billing",
    cancellationPhone: null,
    cancellationEmail: null,
    cancellationSteps: [
      { step: 1, instruction: "Go to github.com > Settings > Billing and plans" },
      { step: 2, instruction: "Under Copilot, click 'Cancel'" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "1Password",
    slug: "1password",
    category: "Security",
    avgMonthlyPrice: 2.99,
    difficultyScore: 2.0,
    darkPatternScore: 2.0,
    cancellationUrl: "https://my.1password.com/settings/billing",
    cancellationPhone: null,
    cancellationEmail: "support@1password.com",
    cancellationSteps: [
      { step: 1, instruction: "Go to my.1password.com > Settings > Billing" },
      { step: 2, instruction: "Click 'Cancel subscription'" },
      { step: 3, instruction: "Export your passwords first!" },
    ],
  },
  {
    name: "Dashlane",
    slug: "dashlane",
    category: "Security",
    avgMonthlyPrice: 4.99,
    difficultyScore: 2.5,
    darkPatternScore: 3.0,
    cancellationUrl: null,
    cancellationPhone: null,
    cancellationEmail: "support@dashlane.com",
    cancellationSteps: [
      { step: 1, instruction: "Go to app.dashlane.com > Account > Subscription" },
      { step: 2, instruction: "Click 'Cancel subscription'" },
      { step: 3, instruction: "Navigate retention screens and confirm" },
    ],
  },
];

async function main() {
  console.log("Seeding database...");

  for (const company of companies) {
    await prisma.saasCompany.upsert({
      where: { slug: company.slug },
      update: {
        name: company.name,
        category: company.category,
        avgMonthlyPrice: company.avgMonthlyPrice,
        difficultyScore: company.difficultyScore,
        darkPatternScore: company.darkPatternScore,
        cancellationUrl: company.cancellationUrl,
        cancellationPhone: company.cancellationPhone,
        cancellationEmail: company.cancellationEmail,
        cancellationSteps: company.cancellationSteps,
      },
      create: {
        name: company.name,
        slug: company.slug,
        category: company.category,
        avgMonthlyPrice: company.avgMonthlyPrice,
        difficultyScore: company.difficultyScore,
        darkPatternScore: company.darkPatternScore,
        cancellationUrl: company.cancellationUrl,
        cancellationPhone: company.cancellationPhone,
        cancellationEmail: company.cancellationEmail,
        cancellationSteps: company.cancellationSteps,
        totalCancellations: Math.floor(Math.random() * 5000) + 100,
      },
    });
    console.log(`  Seeded: ${company.name}`);
  }

  console.log(`Seeded ${companies.length} companies`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
