import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

type Co = { name: string; slug: string; category: string; regions: string[]; price: number; hq: string };
type CatTpl = { diff: [number, number]; dark: [number, number]; methods: string[]; patterns: string[][] };

const tpl: Record<string, CatTpl> = {
  "VPN": { diff: [1.5, 3.5], dark: [2, 6], methods: ["online"], patterns: [["Auto-renewal"], ["Retention offers"], ["Confirmshaming"]] },
  "Meal Kit": { diff: [2.5, 4.5], dark: [4, 8], methods: ["online", "phone"], patterns: [["Skip-only option"], ["Pause instead of cancel"], ["Retention offers"]] },
  "Pet Services": { diff: [2, 4], dark: [3, 6], methods: ["online", "phone"], patterns: [["Retention offers"], ["Confirmshaming"]] },
  "Car Insurance": { diff: [3, 5], dark: [4, 7], methods: ["phone", "mail"], patterns: [["Phone-only"], ["Retention offers"], ["Penalty clauses"]] },
  "Home Security": { diff: [4, 5], dark: [6, 9], methods: ["phone"], patterns: [["Long contracts"], ["Early termination fees"], ["Phone-only"]] },
  "Marketing Tools": { diff: [2, 4], dark: [3, 6], methods: ["online"], patterns: [["Annual lock-in"], ["Retention offers"]] },
  "HR/Payroll": { diff: [3, 4.5], dark: [4, 7], methods: ["online", "phone"], patterns: [["Contract terms"], ["Data export fees"]] },
  "Hosting/Domains": { diff: [2, 4], dark: [4, 7], methods: ["online"], patterns: [["Domain lock-in"], ["Auto-renewal"], ["Upselling"]] },
  "Phone Plans": { diff: [3.5, 5], dark: [5, 8], methods: ["phone", "store"], patterns: [["Contract penalties"], ["Phone-only"], ["Retention offers"]] },
  "ISP": { diff: [4, 5], dark: [6, 9], methods: ["phone"], patterns: [["Equipment return"], ["Early termination"], ["Phone-only"]] },
  "Gym Chains": { diff: [3.5, 5], dark: [5, 9], methods: ["mail", "in-person"], patterns: [["Certified mail only"], ["In-person only"], ["30-day notice"]] },
  "Dating Apps": { diff: [2, 4], dark: [4, 7], methods: ["online"], patterns: [["Confirmshaming"], ["Hidden settings"], ["Retention offers"]] },
  "Education/Learning": { diff: [2, 3.5], dark: [3, 6], methods: ["online"], patterns: [["Annual billing"], ["Retention offers"]] },
  "Password Managers": { diff: [1.5, 3], dark: [2, 4], methods: ["online"], patterns: [["Data export warnings"], ["Retention offers"]] },
  "Project Management": { diff: [2, 3.5], dark: [3, 5], methods: ["online"], patterns: [["Team data warnings"], ["Retention offers"]] },
  "CRM Software": { diff: [2.5, 4], dark: [4, 6], methods: ["online", "phone"], patterns: [["Data export fees"], ["Contract terms"]] },
  "Accounting Software": { diff: [2.5, 4], dark: [4, 6], methods: ["online"], patterns: [["Tax season lock-in"], ["Data export"]] },
  "Design Tools": { diff: [2.5, 4.5], dark: [4, 8], methods: ["online"], patterns: [["Annual commitment"], ["Early termination fees"]] },
  "Video Conferencing": { diff: [2, 3], dark: [2, 4], methods: ["online"], patterns: [["Retention offers"]] },
  "Cloud Backup": { diff: [2, 3.5], dark: [3, 5], methods: ["online"], patterns: [["Data deletion warnings"], ["Retention offers"]] },
  "Antivirus": { diff: [3, 4.5], dark: [5, 9], methods: ["online", "phone"], patterns: [["Scare tactics"], ["Auto-renewal"], ["Retention offers"]] },
  "Music Streaming": { diff: [1.5, 3], dark: [2, 5], methods: ["online"], patterns: [["Confirmshaming"], ["Retention offers"]] },
  "Audiobooks": { diff: [2, 3.5], dark: [3, 5], methods: ["online"], patterns: [["Credit loss warnings"], ["Retention offers"]] },
  "News/Magazines": { diff: [2.5, 4], dark: [4, 7], methods: ["online", "phone"], patterns: [["Phone-only"], ["Retention offers"]] },
  "Meditation Apps": { diff: [2, 3], dark: [3, 5], methods: ["online"], patterns: [["Annual billing"], ["Confirmshaming"]] },
  "Language Learning": { diff: [2, 3.5], dark: [3, 6], methods: ["online"], patterns: [["Progress loss warnings"], ["Annual lock-in"]] },
  "Health/Wellness": { diff: [2, 3.5], dark: [3, 6], methods: ["online"], patterns: [["Annual billing"], ["Retention offers"]] },
  "Streaming": { diff: [1.5, 3], dark: [2, 5], methods: ["online"], patterns: [["Confirmshaming"], ["Hidden cancel"]] },
  "E-commerce": { diff: [2, 3.5], dark: [3, 6], methods: ["online"], patterns: [["Auto-renewal"], ["Hidden settings"]] },
  "Travel": { diff: [2, 4], dark: [3, 6], methods: ["online", "phone"], patterns: [["Retention offers"], ["Annual lock-in"]] },
  "Fitness App": { diff: [2, 3.5], dark: [3, 6], methods: ["online"], patterns: [["Annual billing"], ["Confirmshaming"]] },
};

const companies: Co[] = [
  // VPN (15)
  { name: "ExpressVPN", slug: "expressvpn", category: "VPN", regions: ["GLOBAL"], price: 12.95, hq: "BVI" },
  { name: "NordVPN", slug: "nordvpn", category: "VPN", regions: ["GLOBAL"], price: 11.99, hq: "Panama" },
  { name: "Surfshark", slug: "surfshark", category: "VPN", regions: ["GLOBAL"], price: 12.95, hq: "Netherlands" },
  { name: "CyberGhost", slug: "cyberghost", category: "VPN", regions: ["GLOBAL"], price: 12.99, hq: "Romania" },
  { name: "Private Internet Access", slug: "pia-vpn", category: "VPN", regions: ["GLOBAL"], price: 11.95, hq: "US" },
  { name: "IPVanish", slug: "ipvanish", category: "VPN", regions: ["GLOBAL"], price: 11.99, hq: "US" },
  { name: "ProtonVPN", slug: "protonvpn", category: "VPN", regions: ["GLOBAL"], price: 9.99, hq: "Switzerland" },
  { name: "Windscribe", slug: "windscribe", category: "VPN", regions: ["GLOBAL"], price: 9.00, hq: "Canada" },
  { name: "TunnelBear", slug: "tunnelbear", category: "VPN", regions: ["GLOBAL"], price: 9.99, hq: "Canada" },
  { name: "Hotspot Shield", slug: "hotspot-shield", category: "VPN", regions: ["GLOBAL"], price: 12.99, hq: "US" },
  { name: "VyprVPN", slug: "vyprvpn", category: "VPN", regions: ["GLOBAL"], price: 12.95, hq: "Switzerland" },
  { name: "Mullvad VPN", slug: "mullvad-vpn", category: "VPN", regions: ["GLOBAL"], price: 5.00, hq: "Sweden" },
  { name: "IVPN", slug: "ivpn", category: "VPN", regions: ["GLOBAL"], price: 6.00, hq: "Gibraltar" },
  { name: "Atlas VPN", slug: "atlas-vpn", category: "VPN", regions: ["GLOBAL"], price: 10.99, hq: "US" },
  { name: "PureVPN", slug: "purevpn", category: "VPN", regions: ["GLOBAL"], price: 10.95, hq: "Hong Kong" },
  // Meal Kit (18)
  { name: "HelloFresh", slug: "hellofresh", category: "Meal Kit", regions: ["US", "UK", "EU", "AU", "CANADA"], price: 59.94, hq: "Germany" },
  { name: "Blue Apron", slug: "blue-apron", category: "Meal Kit", regions: ["US"], price: 47.95, hq: "US" },
  { name: "Home Chef", slug: "home-chef", category: "Meal Kit", regions: ["US"], price: 51.92, hq: "US" },
  { name: "Sunbasket", slug: "sunbasket", category: "Meal Kit", regions: ["US"], price: 71.94, hq: "US" },
  { name: "Green Chef", slug: "green-chef", category: "Meal Kit", regions: ["US", "UK"], price: 71.94, hq: "US" },
  { name: "EveryPlate", slug: "everyplate", category: "Meal Kit", regions: ["US"], price: 38.93, hq: "US" },
  { name: "Dinnerly", slug: "dinnerly", category: "Meal Kit", regions: ["US", "AU"], price: 38.93, hq: "US" },
  { name: "Marley Spoon", slug: "marley-spoon", category: "Meal Kit", regions: ["US", "AU", "EU"], price: 55.92, hq: "Germany" },
  { name: "Factor", slug: "factor-meals", category: "Meal Kit", regions: ["US"], price: 77.00, hq: "US" },
  { name: "Freshly", slug: "freshly", category: "Meal Kit", regions: ["US"], price: 49.99, hq: "US" },
  { name: "Gobble", slug: "gobble", category: "Meal Kit", regions: ["US"], price: 71.94, hq: "US" },
  { name: "Purple Carrot", slug: "purple-carrot", category: "Meal Kit", regions: ["US"], price: 71.94, hq: "US" },
  { name: "Hungryroot", slug: "hungryroot", category: "Meal Kit", regions: ["US"], price: 65.00, hq: "US" },
  { name: "Trifecta", slug: "trifecta", category: "Meal Kit", regions: ["US"], price: 108.43, hq: "US" },
  { name: "Snap Kitchen", slug: "snap-kitchen", category: "Meal Kit", regions: ["US"], price: 89.00, hq: "US" },
  { name: "Gousto", slug: "gousto", category: "Meal Kit", regions: ["UK"], price: 34.99, hq: "UK" },
  { name: "Mindful Chef", slug: "mindful-chef", category: "Meal Kit", regions: ["UK"], price: 45.00, hq: "UK" },
  { name: "SimplyCook", slug: "simplycook", category: "Meal Kit", regions: ["UK"], price: 9.99, hq: "UK" },
  // Pet Services (13)
  { name: "BarkBox", slug: "barkbox", category: "Pet Services", regions: ["US", "UK", "CANADA"], price: 35.00, hq: "US" },
  { name: "Chewy Autoship", slug: "chewy-autoship", category: "Pet Services", regions: ["US"], price: 50.00, hq: "US" },
  { name: "PetPlate", slug: "petplate", category: "Pet Services", regions: ["US"], price: 75.00, hq: "US" },
  { name: "The Farmer's Dog", slug: "farmers-dog", category: "Pet Services", regions: ["US"], price: 60.00, hq: "US" },
  { name: "Ollie", slug: "ollie-pet", category: "Pet Services", regions: ["US"], price: 72.00, hq: "US" },
  { name: "NomNomNow", slug: "nomnomnow", category: "Pet Services", regions: ["US"], price: 65.00, hq: "US" },
  { name: "Spot & Tango", slug: "spot-tango", category: "Pet Services", regions: ["US"], price: 70.00, hq: "US" },
  { name: "Butternut Box", slug: "butternut-box", category: "Pet Services", regions: ["UK"], price: 45.00, hq: "UK" },
  { name: "Tails.com", slug: "tails-com", category: "Pet Services", regions: ["UK", "EU"], price: 35.00, hq: "UK" },
  { name: "Lemonade Pet", slug: "lemonade-pet", category: "Pet Services", regions: ["US"], price: 25.00, hq: "US" },
  { name: "Petcube Care", slug: "petcube-care", category: "Pet Services", regions: ["GLOBAL"], price: 10.00, hq: "US" },
  { name: "Wisdom Panel", slug: "wisdom-panel", category: "Pet Services", regions: ["US", "UK"], price: 99.00, hq: "US" },
  { name: "Embark DNA", slug: "embark-dna", category: "Pet Services", regions: ["US"], price: 129.00, hq: "US" },
  // Car Insurance (13)
  { name: "Geico", slug: "geico", category: "Car Insurance", regions: ["US"], price: 150.00, hq: "US" },
  { name: "Progressive", slug: "progressive", category: "Car Insurance", regions: ["US"], price: 145.00, hq: "US" },
  { name: "State Farm", slug: "state-farm", category: "Car Insurance", regions: ["US"], price: 160.00, hq: "US" },
  { name: "Allstate", slug: "allstate", category: "Car Insurance", regions: ["US"], price: 175.00, hq: "US" },
  { name: "Liberty Mutual", slug: "liberty-mutual", category: "Car Insurance", regions: ["US"], price: 165.00, hq: "US" },
  { name: "USAA", slug: "usaa", category: "Car Insurance", regions: ["US"], price: 125.00, hq: "US" },
  { name: "Nationwide", slug: "nationwide", category: "Car Insurance", regions: ["US"], price: 155.00, hq: "US" },
  { name: "Farmers Insurance", slug: "farmers-insurance", category: "Car Insurance", regions: ["US"], price: 170.00, hq: "US" },
  { name: "Root Insurance", slug: "root-insurance", category: "Car Insurance", regions: ["US"], price: 100.00, hq: "US" },
  { name: "Metromile", slug: "metromile", category: "Car Insurance", regions: ["US"], price: 80.00, hq: "US" },
  { name: "Admiral", slug: "admiral-insurance", category: "Car Insurance", regions: ["UK"], price: 85.00, hq: "UK" },
  { name: "Direct Line", slug: "direct-line", category: "Car Insurance", regions: ["UK"], price: 90.00, hq: "UK" },
  { name: "Aviva", slug: "aviva-car", category: "Car Insurance", regions: ["UK"], price: 95.00, hq: "UK" },
  // Home Security (13)
  { name: "ADT", slug: "adt-security", category: "Home Security", regions: ["US", "UK", "CANADA"], price: 45.99, hq: "US" },
  { name: "Vivint", slug: "vivint", category: "Home Security", regions: ["US", "CANADA"], price: 39.99, hq: "US" },
  { name: "SimpliSafe", slug: "simplisafe", category: "Home Security", regions: ["US", "UK"], price: 24.99, hq: "US" },
  { name: "Ring Protect", slug: "ring-protect", category: "Home Security", regions: ["US", "UK", "EU", "AU"], price: 10.00, hq: "US" },
  { name: "Nest Aware", slug: "nest-aware", category: "Home Security", regions: ["US", "UK", "EU", "AU"], price: 12.00, hq: "US" },
  { name: "Frontpoint", slug: "frontpoint", category: "Home Security", regions: ["US"], price: 44.99, hq: "US" },
  { name: "Brinks Home", slug: "brinks-home", category: "Home Security", regions: ["US"], price: 39.00, hq: "US" },
  { name: "Abode", slug: "abode-security", category: "Home Security", regions: ["US"], price: 20.00, hq: "US" },
  { name: "Cove Security", slug: "cove-security", category: "Home Security", regions: ["US"], price: 17.99, hq: "US" },
  { name: "Scout Alarm", slug: "scout-alarm", category: "Home Security", regions: ["US"], price: 19.99, hq: "US" },
  { name: "Arlo Secure", slug: "arlo-secure", category: "Home Security", regions: ["US", "UK", "EU"], price: 12.99, hq: "US" },
  { name: "Wyze Cam Plus", slug: "wyze-cam-plus", category: "Home Security", regions: ["US"], price: 1.99, hq: "US" },
  { name: "Eufy Security", slug: "eufy-security", category: "Home Security", regions: ["US", "UK", "EU"], price: 9.99, hq: "China" },
  // Marketing Tools (20)
  { name: "Mailchimp", slug: "mailchimp", category: "Marketing Tools", regions: ["GLOBAL"], price: 20.00, hq: "US" },
  { name: "HubSpot Marketing", slug: "hubspot-marketing", category: "Marketing Tools", regions: ["GLOBAL"], price: 45.00, hq: "US" },
  { name: "Constant Contact", slug: "constant-contact", category: "Marketing Tools", regions: ["GLOBAL"], price: 20.00, hq: "US" },
  { name: "Klaviyo", slug: "klaviyo", category: "Marketing Tools", regions: ["GLOBAL"], price: 45.00, hq: "US" },
  { name: "ActiveCampaign", slug: "activecampaign", category: "Marketing Tools", regions: ["GLOBAL"], price: 29.00, hq: "US" },
  { name: "ConvertKit", slug: "convertkit", category: "Marketing Tools", regions: ["GLOBAL"], price: 29.00, hq: "US" },
  { name: "Drip", slug: "drip-email", category: "Marketing Tools", regions: ["GLOBAL"], price: 39.00, hq: "US" },
  { name: "GetResponse", slug: "getresponse", category: "Marketing Tools", regions: ["GLOBAL"], price: 19.00, hq: "Poland" },
  { name: "AWeber", slug: "aweber", category: "Marketing Tools", regions: ["GLOBAL"], price: 19.99, hq: "US" },
  { name: "Sendinblue", slug: "sendinblue", category: "Marketing Tools", regions: ["GLOBAL"], price: 25.00, hq: "France" },
  { name: "Moosend", slug: "moosend", category: "Marketing Tools", regions: ["GLOBAL"], price: 9.00, hq: "UK" },
  { name: "Omnisend", slug: "omnisend", category: "Marketing Tools", regions: ["GLOBAL"], price: 16.00, hq: "Lithuania" },
  { name: "Campaign Monitor", slug: "campaign-monitor", category: "Marketing Tools", regions: ["GLOBAL"], price: 9.00, hq: "Australia" },
  { name: "Benchmark Email", slug: "benchmark-email", category: "Marketing Tools", regions: ["GLOBAL"], price: 13.00, hq: "US" },
  { name: "MailerLite", slug: "mailerlite", category: "Marketing Tools", regions: ["GLOBAL"], price: 10.00, hq: "Lithuania" },
  { name: "Hootsuite", slug: "hootsuite", category: "Marketing Tools", regions: ["GLOBAL"], price: 99.00, hq: "Canada" },
  { name: "Buffer", slug: "buffer", category: "Marketing Tools", regions: ["GLOBAL"], price: 6.00, hq: "US" },
  { name: "Sprout Social", slug: "sprout-social", category: "Marketing Tools", regions: ["GLOBAL"], price: 249.00, hq: "US" },
  { name: "Later", slug: "later-social", category: "Marketing Tools", regions: ["GLOBAL"], price: 18.00, hq: "Canada" },
  { name: "Planoly", slug: "planoly", category: "Marketing Tools", regions: ["GLOBAL"], price: 13.00, hq: "US" },
  // HR/Payroll (13)
  { name: "Gusto", slug: "gusto-payroll", category: "HR/Payroll", regions: ["US"], price: 40.00, hq: "US" },
  { name: "ADP", slug: "adp-payroll", category: "HR/Payroll", regions: ["US", "GLOBAL"], price: 79.00, hq: "US" },
  { name: "Paychex", slug: "paychex", category: "HR/Payroll", regions: ["US"], price: 59.00, hq: "US" },
  { name: "Rippling", slug: "rippling", category: "HR/Payroll", regions: ["US"], price: 8.00, hq: "US" },
  { name: "Zenefits", slug: "zenefits", category: "HR/Payroll", regions: ["US"], price: 10.00, hq: "US" },
  { name: "BambooHR", slug: "bamboohr", category: "HR/Payroll", regions: ["US", "UK"], price: 99.00, hq: "US" },
  { name: "Namely", slug: "namely-hr", category: "HR/Payroll", regions: ["US"], price: 12.00, hq: "US" },
  { name: "Justworks", slug: "justworks", category: "HR/Payroll", regions: ["US"], price: 59.00, hq: "US" },
  { name: "Deel", slug: "deel", category: "HR/Payroll", regions: ["GLOBAL"], price: 49.00, hq: "US" },
  { name: "Remote.com", slug: "remote-hr", category: "HR/Payroll", regions: ["GLOBAL"], price: 599.00, hq: "US" },
  { name: "Oyster HR", slug: "oyster-hr", category: "HR/Payroll", regions: ["GLOBAL"], price: 499.00, hq: "US" },
  { name: "Papaya Global", slug: "papaya-global", category: "HR/Payroll", regions: ["GLOBAL"], price: 20.00, hq: "Israel" },
  { name: "Sage HR", slug: "sage-hr", category: "HR/Payroll", regions: ["UK", "EU"], price: 5.50, hq: "UK" },
  // Hosting/Domains (20)
  { name: "GoDaddy", slug: "godaddy", category: "Hosting/Domains", regions: ["GLOBAL"], price: 11.99, hq: "US" },
  { name: "Namecheap", slug: "namecheap", category: "Hosting/Domains", regions: ["GLOBAL"], price: 8.88, hq: "US" },
  { name: "Bluehost", slug: "bluehost", category: "Hosting/Domains", regions: ["GLOBAL"], price: 2.95, hq: "US" },
  { name: "HostGator", slug: "hostgator", category: "Hosting/Domains", regions: ["GLOBAL"], price: 2.75, hq: "US" },
  { name: "SiteGround", slug: "siteground", category: "Hosting/Domains", regions: ["GLOBAL"], price: 2.99, hq: "Bulgaria" },
  { name: "DreamHost", slug: "dreamhost", category: "Hosting/Domains", regions: ["GLOBAL"], price: 2.59, hq: "US" },
  { name: "A2 Hosting", slug: "a2-hosting", category: "Hosting/Domains", regions: ["GLOBAL"], price: 2.99, hq: "US" },
  { name: "InMotion Hosting", slug: "inmotion-hosting", category: "Hosting/Domains", regions: ["GLOBAL"], price: 2.29, hq: "US" },
  { name: "Hostinger", slug: "hostinger", category: "Hosting/Domains", regions: ["GLOBAL"], price: 1.99, hq: "Lithuania" },
  { name: "Cloudways", slug: "cloudways", category: "Hosting/Domains", regions: ["GLOBAL"], price: 14.00, hq: "Malta" },
  { name: "WP Engine", slug: "wp-engine", category: "Hosting/Domains", regions: ["GLOBAL"], price: 25.00, hq: "US" },
  { name: "Kinsta", slug: "kinsta", category: "Hosting/Domains", regions: ["GLOBAL"], price: 35.00, hq: "US" },
  { name: "Flywheel", slug: "flywheel-hosting", category: "Hosting/Domains", regions: ["GLOBAL"], price: 15.00, hq: "US" },
  { name: "Liquid Web", slug: "liquid-web", category: "Hosting/Domains", regions: ["GLOBAL"], price: 15.00, hq: "US" },
  { name: "Nexcess", slug: "nexcess", category: "Hosting/Domains", regions: ["GLOBAL"], price: 13.30, hq: "US" },
  { name: "Pressable", slug: "pressable", category: "Hosting/Domains", regions: ["GLOBAL"], price: 25.00, hq: "US" },
  { name: "Pagely", slug: "pagely", category: "Hosting/Domains", regions: ["GLOBAL"], price: 199.00, hq: "US" },
  { name: "Google Domains", slug: "google-domains", category: "Hosting/Domains", regions: ["GLOBAL"], price: 12.00, hq: "US" },
  { name: "Hover", slug: "hover-domains", category: "Hosting/Domains", regions: ["GLOBAL"], price: 15.00, hq: "Canada" },
  { name: "Porkbun", slug: "porkbun", category: "Hosting/Domains", regions: ["GLOBAL"], price: 9.73, hq: "US" },
  // Dating Apps (14)
  { name: "Tinder Plus", slug: "tinder-plus", category: "Dating Apps", regions: ["GLOBAL"], price: 19.99, hq: "US" },
  { name: "Tinder Gold", slug: "tinder-gold", category: "Dating Apps", regions: ["GLOBAL"], price: 29.99, hq: "US" },
  { name: "Bumble Premium", slug: "bumble-premium", category: "Dating Apps", regions: ["GLOBAL"], price: 32.99, hq: "US" },
  { name: "Hinge Preferred", slug: "hinge-preferred", category: "Dating Apps", regions: ["GLOBAL"], price: 29.99, hq: "US" },
  { name: "Match.com", slug: "match-com", category: "Dating Apps", regions: ["GLOBAL"], price: 35.99, hq: "US" },
  { name: "eHarmony", slug: "eharmony", category: "Dating Apps", regions: ["GLOBAL"], price: 35.90, hq: "US" },
  { name: "OkCupid Premium", slug: "okcupid-premium", category: "Dating Apps", regions: ["GLOBAL"], price: 34.99, hq: "US" },
  { name: "Plenty of Fish", slug: "plenty-of-fish", category: "Dating Apps", regions: ["GLOBAL"], price: 19.35, hq: "Canada" },
  { name: "Coffee Meets Bagel", slug: "coffee-meets-bagel", category: "Dating Apps", regions: ["GLOBAL"], price: 34.99, hq: "US" },
  { name: "The League", slug: "the-league", category: "Dating Apps", regions: ["US", "UK"], price: 99.99, hq: "US" },
  { name: "Raya", slug: "raya-dating", category: "Dating Apps", regions: ["GLOBAL"], price: 9.99, hq: "US" },
  { name: "Feeld", slug: "feeld", category: "Dating Apps", regions: ["GLOBAL"], price: 14.99, hq: "UK" },
  { name: "Grindr XTRA", slug: "grindr-xtra", category: "Dating Apps", regions: ["GLOBAL"], price: 24.99, hq: "US" },
  { name: "HER Premium", slug: "her-premium", category: "Dating Apps", regions: ["GLOBAL"], price: 14.99, hq: "US" },
  // Language Learning (5)
  { name: "Duolingo Plus", slug: "duolingo-plus", category: "Language Learning", regions: ["GLOBAL"], price: 12.99, hq: "US" },
  { name: "Babbel", slug: "babbel", category: "Language Learning", regions: ["GLOBAL"], price: 13.95, hq: "Germany" },
  { name: "Rosetta Stone", slug: "rosetta-stone", category: "Language Learning", regions: ["GLOBAL"], price: 11.99, hq: "US" },
  { name: "Busuu Premium", slug: "busuu-premium", category: "Language Learning", regions: ["GLOBAL"], price: 9.99, hq: "UK" },
  { name: "Pimsleur", slug: "pimsleur", category: "Language Learning", regions: ["GLOBAL"], price: 19.95, hq: "US" },
  // Education/Learning (14)
  { name: "Coursera Plus", slug: "coursera-plus", category: "Education/Learning", regions: ["GLOBAL"], price: 59.00, hq: "US" },
  { name: "Udemy Pro", slug: "udemy-pro", category: "Education/Learning", regions: ["GLOBAL"], price: 30.00, hq: "US" },
  { name: "LinkedIn Learning", slug: "linkedin-learning", category: "Education/Learning", regions: ["GLOBAL"], price: 29.99, hq: "US" },
  { name: "Skillshare Premium", slug: "skillshare-premium", category: "Education/Learning", regions: ["GLOBAL"], price: 13.99, hq: "US" },
  { name: "MasterClass", slug: "masterclass", category: "Education/Learning", regions: ["GLOBAL"], price: 15.00, hq: "US" },
  { name: "Brilliant", slug: "brilliant", category: "Education/Learning", regions: ["GLOBAL"], price: 24.99, hq: "US" },
  { name: "Khan Academy", slug: "khan-academy", category: "Education/Learning", regions: ["GLOBAL"], price: 0, hq: "US" },
  { name: "Codecademy Pro", slug: "codecademy-pro", category: "Education/Learning", regions: ["GLOBAL"], price: 19.99, hq: "US" },
  { name: "DataCamp", slug: "datacamp", category: "Education/Learning", regions: ["GLOBAL"], price: 25.00, hq: "US" },
  { name: "Pluralsight", slug: "pluralsight", category: "Education/Learning", regions: ["GLOBAL"], price: 29.00, hq: "US" },
  { name: "Treehouse", slug: "treehouse", category: "Education/Learning", regions: ["GLOBAL"], price: 25.00, hq: "US" },
  { name: "Udacity", slug: "udacity", category: "Education/Learning", regions: ["GLOBAL"], price: 399.00, hq: "US" },
  { name: "edX Plus", slug: "edx-plus", category: "Education/Learning", regions: ["GLOBAL"], price: 39.00, hq: "US" },
  { name: "FutureLearn", slug: "futurelearn", category: "Education/Learning", regions: ["GLOBAL"], price: 13.99, hq: "UK" },
  // Password Managers (9)
  { name: "1Password", slug: "1password", category: "Password Managers", regions: ["GLOBAL"], price: 2.99, hq: "Canada" },
  { name: "LastPass Premium", slug: "lastpass-premium", category: "Password Managers", regions: ["GLOBAL"], price: 3.00, hq: "US" },
  { name: "Dashlane Premium", slug: "dashlane-premium", category: "Password Managers", regions: ["GLOBAL"], price: 4.99, hq: "US" },
  { name: "Bitwarden Premium", slug: "bitwarden-premium", category: "Password Managers", regions: ["GLOBAL"], price: 0.83, hq: "US" },
  { name: "Keeper", slug: "keeper-password", category: "Password Managers", regions: ["GLOBAL"], price: 2.91, hq: "US" },
  { name: "NordPass", slug: "nordpass", category: "Password Managers", regions: ["GLOBAL"], price: 2.49, hq: "Panama" },
  { name: "RoboForm", slug: "roboform", category: "Password Managers", regions: ["GLOBAL"], price: 1.99, hq: "US" },
  { name: "Sticky Password", slug: "sticky-password", category: "Password Managers", regions: ["GLOBAL"], price: 2.50, hq: "Czech Republic" },
  { name: "Enpass", slug: "enpass", category: "Password Managers", regions: ["GLOBAL"], price: 1.99, hq: "India" },
  // Project Management (13)
  { name: "Asana Premium", slug: "asana-premium", category: "Project Management", regions: ["GLOBAL"], price: 10.99, hq: "US" },
  { name: "Monday.com", slug: "monday-com", category: "Project Management", regions: ["GLOBAL"], price: 8.00, hq: "Israel" },
  { name: "Trello Premium", slug: "trello-premium", category: "Project Management", regions: ["GLOBAL"], price: 10.00, hq: "US" },
  { name: "Basecamp", slug: "basecamp", category: "Project Management", regions: ["GLOBAL"], price: 99.00, hq: "US" },
  { name: "ClickUp", slug: "clickup", category: "Project Management", regions: ["GLOBAL"], price: 7.00, hq: "US" },
  { name: "Notion Plus", slug: "notion-plus", category: "Project Management", regions: ["GLOBAL"], price: 8.00, hq: "US" },
  { name: "Wrike", slug: "wrike", category: "Project Management", regions: ["GLOBAL"], price: 9.80, hq: "US" },
  { name: "Smartsheet", slug: "smartsheet", category: "Project Management", regions: ["GLOBAL"], price: 9.00, hq: "US" },
  { name: "Teamwork", slug: "teamwork", category: "Project Management", regions: ["GLOBAL"], price: 10.00, hq: "Ireland" },
  { name: "Airtable Plus", slug: "airtable-plus", category: "Project Management", regions: ["GLOBAL"], price: 10.00, hq: "US" },
  { name: "Coda", slug: "coda-docs", category: "Project Management", regions: ["GLOBAL"], price: 10.00, hq: "US" },
  { name: "Linear", slug: "linear-app", category: "Project Management", regions: ["GLOBAL"], price: 8.00, hq: "US" },
  { name: "Height", slug: "height-app", category: "Project Management", regions: ["GLOBAL"], price: 8.00, hq: "US" },
  // CRM Software (13)
  { name: "Salesforce Essentials", slug: "salesforce-essentials", category: "CRM Software", regions: ["GLOBAL"], price: 25.00, hq: "US" },
  { name: "HubSpot CRM", slug: "hubspot-crm", category: "CRM Software", regions: ["GLOBAL"], price: 45.00, hq: "US" },
  { name: "Zoho CRM", slug: "zoho-crm", category: "CRM Software", regions: ["GLOBAL"], price: 14.00, hq: "India" },
  { name: "Pipedrive", slug: "pipedrive", category: "CRM Software", regions: ["GLOBAL"], price: 14.90, hq: "Estonia" },
  { name: "Freshsales", slug: "freshsales", category: "CRM Software", regions: ["GLOBAL"], price: 15.00, hq: "US" },
  { name: "Copper CRM", slug: "copper-crm", category: "CRM Software", regions: ["GLOBAL"], price: 29.00, hq: "US" },
  { name: "Insightly", slug: "insightly", category: "CRM Software", regions: ["GLOBAL"], price: 29.00, hq: "US" },
  { name: "Nimble", slug: "nimble-crm", category: "CRM Software", regions: ["GLOBAL"], price: 24.90, hq: "US" },
  { name: "Nutshell", slug: "nutshell-crm", category: "CRM Software", regions: ["GLOBAL"], price: 19.00, hq: "US" },
  { name: "Close CRM", slug: "close-crm", category: "CRM Software", regions: ["GLOBAL"], price: 29.00, hq: "US" },
  { name: "Keap", slug: "keap-crm", category: "CRM Software", regions: ["GLOBAL"], price: 79.00, hq: "US" },
  { name: "Agile CRM", slug: "agile-crm", category: "CRM Software", regions: ["GLOBAL"], price: 8.99, hq: "US" },
  { name: "Capsule CRM", slug: "capsule-crm", category: "CRM Software", regions: ["GLOBAL"], price: 18.00, hq: "UK" },
  // Accounting Software (10)
  { name: "QuickBooks Online", slug: "quickbooks-online", category: "Accounting Software", regions: ["US", "UK", "CANADA", "AU"], price: 30.00, hq: "US" },
  { name: "Xero", slug: "xero", category: "Accounting Software", regions: ["GLOBAL"], price: 13.00, hq: "New Zealand" },
  { name: "FreshBooks", slug: "freshbooks", category: "Accounting Software", regions: ["GLOBAL"], price: 17.00, hq: "Canada" },
  { name: "Wave Accounting", slug: "wave-accounting", category: "Accounting Software", regions: ["US", "CANADA"], price: 0, hq: "Canada" },
  { name: "Sage Business Cloud", slug: "sage-business-cloud", category: "Accounting Software", regions: ["GLOBAL"], price: 25.00, hq: "UK" },
  { name: "Zoho Books", slug: "zoho-books", category: "Accounting Software", regions: ["GLOBAL"], price: 15.00, hq: "India" },
  { name: "Kashoo", slug: "kashoo", category: "Accounting Software", regions: ["US", "CANADA"], price: 19.95, hq: "Canada" },
  { name: "ZipBooks", slug: "zipbooks", category: "Accounting Software", regions: ["US"], price: 15.00, hq: "US" },
  { name: "Bench", slug: "bench-accounting", category: "Accounting Software", regions: ["US", "CANADA"], price: 299.00, hq: "Canada" },
  { name: "Pilot", slug: "pilot-accounting", category: "Accounting Software", regions: ["US"], price: 599.00, hq: "US" },
  // Design Tools (13)
  { name: "Adobe Creative Cloud", slug: "adobe-creative-cloud", category: "Design Tools", regions: ["GLOBAL"], price: 54.99, hq: "US" },
  { name: "Figma Professional", slug: "figma-professional", category: "Design Tools", regions: ["GLOBAL"], price: 12.00, hq: "US" },
  { name: "Sketch", slug: "sketch-app", category: "Design Tools", regions: ["GLOBAL"], price: 10.00, hq: "Netherlands" },
  { name: "Canva Pro", slug: "canva-pro", category: "Design Tools", regions: ["GLOBAL"], price: 12.99, hq: "Australia" },
  { name: "InVision", slug: "invision", category: "Design Tools", regions: ["GLOBAL"], price: 15.00, hq: "US" },
  { name: "Affinity Designer", slug: "affinity-designer", category: "Design Tools", regions: ["GLOBAL"], price: 69.99, hq: "UK" },
  { name: "Procreate", slug: "procreate", category: "Design Tools", regions: ["GLOBAL"], price: 12.99, hq: "Australia" },
  { name: "Framer", slug: "framer", category: "Design Tools", regions: ["GLOBAL"], price: 15.00, hq: "Netherlands" },
  { name: "Webflow", slug: "webflow", category: "Design Tools", regions: ["GLOBAL"], price: 14.00, hq: "US" },
  { name: "Miro", slug: "miro", category: "Design Tools", regions: ["GLOBAL"], price: 8.00, hq: "US" },
  { name: "Lucidchart", slug: "lucidchart", category: "Design Tools", regions: ["GLOBAL"], price: 7.95, hq: "US" },
  { name: "Whimsical", slug: "whimsical", category: "Design Tools", regions: ["GLOBAL"], price: 10.00, hq: "US" },
  { name: "Loom", slug: "loom", category: "Design Tools", regions: ["GLOBAL"], price: 12.50, hq: "US" },
  // Video Conferencing (9)
  { name: "Zoom Pro", slug: "zoom-pro", category: "Video Conferencing", regions: ["GLOBAL"], price: 15.99, hq: "US" },
  { name: "Microsoft Teams", slug: "microsoft-teams", category: "Video Conferencing", regions: ["GLOBAL"], price: 4.00, hq: "US" },
  { name: "Google Meet", slug: "google-meet", category: "Video Conferencing", regions: ["GLOBAL"], price: 6.00, hq: "US" },
  { name: "Webex", slug: "webex", category: "Video Conferencing", regions: ["GLOBAL"], price: 13.50, hq: "US" },
  { name: "GoToMeeting", slug: "gotomeeting", category: "Video Conferencing", regions: ["GLOBAL"], price: 12.00, hq: "US" },
  { name: "BlueJeans", slug: "bluejeans", category: "Video Conferencing", regions: ["GLOBAL"], price: 12.49, hq: "US" },
  { name: "RingCentral", slug: "ringcentral", category: "Video Conferencing", regions: ["GLOBAL"], price: 19.99, hq: "US" },
  { name: "Dialpad", slug: "dialpad", category: "Video Conferencing", regions: ["GLOBAL"], price: 15.00, hq: "US" },
  { name: "Around", slug: "around-video", category: "Video Conferencing", regions: ["GLOBAL"], price: 10.00, hq: "US" },
  // Cloud Backup (10)
  { name: "Backblaze", slug: "backblaze", category: "Cloud Backup", regions: ["GLOBAL"], price: 7.00, hq: "US" },
  { name: "Carbonite", slug: "carbonite", category: "Cloud Backup", regions: ["GLOBAL"], price: 6.00, hq: "US" },
  { name: "IDrive", slug: "idrive", category: "Cloud Backup", regions: ["GLOBAL"], price: 4.34, hq: "US" },
  { name: "Acronis", slug: "acronis", category: "Cloud Backup", regions: ["GLOBAL"], price: 4.17, hq: "Switzerland" },
  { name: "SpiderOak", slug: "spideroak", category: "Cloud Backup", regions: ["GLOBAL"], price: 6.00, hq: "US" },
  { name: "Crashplan", slug: "crashplan", category: "Cloud Backup", regions: ["GLOBAL"], price: 10.00, hq: "US" },
  { name: "pCloud", slug: "pcloud", category: "Cloud Backup", regions: ["GLOBAL"], price: 4.99, hq: "Switzerland" },
  { name: "Sync.com", slug: "sync-com", category: "Cloud Backup", regions: ["GLOBAL"], price: 8.00, hq: "Canada" },
  { name: "Tresorit", slug: "tresorit", category: "Cloud Backup", regions: ["GLOBAL"], price: 10.42, hq: "Switzerland" },
  { name: "MEGA", slug: "mega-cloud", category: "Cloud Backup", regions: ["GLOBAL"], price: 4.99, hq: "New Zealand" },
  // Meditation Apps (9)
  { name: "Headspace", slug: "headspace", category: "Meditation Apps", regions: ["GLOBAL"], price: 12.99, hq: "US" },
  { name: "Calm", slug: "calm", category: "Meditation Apps", regions: ["GLOBAL"], price: 14.99, hq: "US" },
  { name: "Insight Timer", slug: "insight-timer", category: "Meditation Apps", regions: ["GLOBAL"], price: 9.99, hq: "Australia" },
  { name: "Ten Percent Happier", slug: "ten-percent-happier", category: "Meditation Apps", regions: ["GLOBAL"], price: 14.99, hq: "US" },
  { name: "Waking Up", slug: "waking-up", category: "Meditation Apps", regions: ["GLOBAL"], price: 14.99, hq: "US" },
  { name: "Simple Habit", slug: "simple-habit", category: "Meditation Apps", regions: ["GLOBAL"], price: 11.99, hq: "US" },
  { name: "Buddhify", slug: "buddhify", category: "Meditation Apps", regions: ["GLOBAL"], price: 4.99, hq: "UK" },
  { name: "Breethe", slug: "breethe", category: "Meditation Apps", regions: ["GLOBAL"], price: 12.99, hq: "US" },
  { name: "Aura", slug: "aura-meditation", category: "Meditation Apps", regions: ["GLOBAL"], price: 11.99, hq: "US" },
  // Audiobooks (7)
  { name: "Audible", slug: "audible", category: "Audiobooks", regions: ["GLOBAL"], price: 14.95, hq: "US" },
  { name: "Scribd", slug: "scribd", category: "Audiobooks", regions: ["GLOBAL"], price: 11.99, hq: "US" },
  { name: "Libro.fm", slug: "libro-fm", category: "Audiobooks", regions: ["US"], price: 14.99, hq: "US" },
  { name: "Kobo Plus", slug: "kobo-plus", category: "Audiobooks", regions: ["GLOBAL"], price: 9.99, hq: "Canada" },
  { name: "Storytel", slug: "storytel", category: "Audiobooks", regions: ["EU", "INDIA"], price: 12.99, hq: "Sweden" },
  { name: "Chirp", slug: "chirp", category: "Audiobooks", regions: ["US"], price: 0, hq: "US" },
  { name: "Audiobooks.com", slug: "audiobooks-com", category: "Audiobooks", regions: ["GLOBAL"], price: 14.95, hq: "US" },
  // News/Magazines (13)
  { name: "New York Times", slug: "nyt-digital", category: "News/Magazines", regions: ["GLOBAL"], price: 17.00, hq: "US" },
  { name: "Washington Post", slug: "washington-post", category: "News/Magazines", regions: ["GLOBAL"], price: 10.00, hq: "US" },
  { name: "Wall Street Journal", slug: "wsj-digital", category: "News/Magazines", regions: ["GLOBAL"], price: 38.99, hq: "US" },
  { name: "The Economist", slug: "the-economist", category: "News/Magazines", regions: ["GLOBAL"], price: 22.00, hq: "UK" },
  { name: "Financial Times", slug: "financial-times", category: "News/Magazines", regions: ["GLOBAL"], price: 39.00, hq: "UK" },
  { name: "The Atlantic", slug: "the-atlantic", category: "News/Magazines", regions: ["GLOBAL"], price: 5.83, hq: "US" },
  { name: "The New Yorker", slug: "the-new-yorker", category: "News/Magazines", regions: ["GLOBAL"], price: 6.99, hq: "US" },
  { name: "Wired", slug: "wired", category: "News/Magazines", regions: ["GLOBAL"], price: 5.00, hq: "US" },
  { name: "Bloomberg", slug: "bloomberg", category: "News/Magazines", regions: ["GLOBAL"], price: 34.99, hq: "US" },
  { name: "The Guardian", slug: "the-guardian", category: "News/Magazines", regions: ["GLOBAL"], price: 10.00, hq: "UK" },
  { name: "The Times UK", slug: "the-times-uk", category: "News/Magazines", regions: ["UK"], price: 26.00, hq: "UK" },
  { name: "Medium", slug: "medium", category: "News/Magazines", regions: ["GLOBAL"], price: 5.00, hq: "US" },
  { name: "Substack", slug: "substack", category: "News/Magazines", regions: ["GLOBAL"], price: 10.00, hq: "US" },
  // Antivirus (11)
  { name: "Norton 360", slug: "norton-360", category: "Antivirus", regions: ["GLOBAL"], price: 9.99, hq: "US" },
  { name: "McAfee Total Protection", slug: "mcafee-total", category: "Antivirus", regions: ["GLOBAL"], price: 8.33, hq: "US" },
  { name: "Bitdefender", slug: "bitdefender", category: "Antivirus", regions: ["GLOBAL"], price: 3.33, hq: "Romania" },
  { name: "Kaspersky", slug: "kaspersky", category: "Antivirus", regions: ["GLOBAL"], price: 4.99, hq: "Russia" },
  { name: "Avast Premium", slug: "avast-premium", category: "Antivirus", regions: ["GLOBAL"], price: 4.19, hq: "Czech Republic" },
  { name: "AVG Ultimate", slug: "avg-ultimate", category: "Antivirus", regions: ["GLOBAL"], price: 4.99, hq: "Czech Republic" },
  { name: "ESET NOD32", slug: "eset-nod32", category: "Antivirus", regions: ["GLOBAL"], price: 3.33, hq: "Slovakia" },
  { name: "Trend Micro", slug: "trend-micro", category: "Antivirus", regions: ["GLOBAL"], price: 2.49, hq: "Japan" },
  { name: "Webroot", slug: "webroot", category: "Antivirus", regions: ["GLOBAL"], price: 2.49, hq: "US" },
  { name: "F-Secure", slug: "f-secure", category: "Antivirus", regions: ["GLOBAL"], price: 4.99, hq: "Finland" },
  { name: "Malwarebytes Premium", slug: "malwarebytes-premium", category: "Antivirus", regions: ["GLOBAL"], price: 3.33, hq: "US" },
  // Music Streaming (9)
  { name: "Spotify Premium", slug: "spotify-premium", category: "Music Streaming", regions: ["GLOBAL"], price: 10.99, hq: "Sweden" },
  { name: "Apple Music", slug: "apple-music", category: "Music Streaming", regions: ["GLOBAL"], price: 10.99, hq: "US" },
  { name: "Amazon Music Unlimited", slug: "amazon-music-unlimited", category: "Music Streaming", regions: ["GLOBAL"], price: 9.99, hq: "US" },
  { name: "YouTube Music Premium", slug: "youtube-music-premium", category: "Music Streaming", regions: ["GLOBAL"], price: 10.99, hq: "US" },
  { name: "Tidal HiFi", slug: "tidal-hifi", category: "Music Streaming", regions: ["GLOBAL"], price: 10.99, hq: "Norway" },
  { name: "Deezer Premium", slug: "deezer-premium", category: "Music Streaming", regions: ["GLOBAL"], price: 10.99, hq: "France" },
  { name: "Pandora Plus", slug: "pandora-plus", category: "Music Streaming", regions: ["US"], price: 4.99, hq: "US" },
  { name: "SoundCloud Go+", slug: "soundcloud-go-plus", category: "Music Streaming", regions: ["GLOBAL"], price: 9.99, hq: "Germany" },
  { name: "Qobuz", slug: "qobuz", category: "Music Streaming", regions: ["GLOBAL"], price: 12.99, hq: "France" },
  // Gym Chains (15)
  { name: "Planet Fitness", slug: "planet-fitness", category: "Gym Chains", regions: ["US", "CANADA"], price: 24.99, hq: "US" },
  { name: "LA Fitness", slug: "la-fitness", category: "Gym Chains", regions: ["US", "CANADA"], price: 34.99, hq: "US" },
  { name: "24 Hour Fitness", slug: "24-hour-fitness", category: "Gym Chains", regions: ["US"], price: 36.99, hq: "US" },
  { name: "Anytime Fitness", slug: "anytime-fitness", category: "Gym Chains", regions: ["GLOBAL"], price: 38.99, hq: "US" },
  { name: "Gold's Gym", slug: "golds-gym", category: "Gym Chains", regions: ["GLOBAL"], price: 29.99, hq: "US" },
  { name: "Equinox", slug: "equinox", category: "Gym Chains", regions: ["US", "UK"], price: 200.00, hq: "US" },
  { name: "Orangetheory", slug: "orangetheory", category: "Gym Chains", regions: ["GLOBAL"], price: 169.00, hq: "US" },
  { name: "CrossFit", slug: "crossfit", category: "Gym Chains", regions: ["GLOBAL"], price: 150.00, hq: "US" },
  { name: "F45 Training", slug: "f45-training", category: "Gym Chains", regions: ["GLOBAL"], price: 199.00, hq: "Australia" },
  { name: "Barry's Bootcamp", slug: "barrys-bootcamp", category: "Gym Chains", regions: ["US", "UK"], price: 250.00, hq: "US" },
  { name: "SoulCycle", slug: "soulcycle", category: "Gym Chains", regions: ["US", "UK"], price: 34.00, hq: "US" },
  { name: "Peloton", slug: "peloton", category: "Gym Chains", regions: ["US", "UK", "CANADA", "AU"], price: 44.00, hq: "US" },
  { name: "ClassPass", slug: "classpass", category: "Gym Chains", regions: ["GLOBAL"], price: 49.00, hq: "US" },
  { name: "PureGym", slug: "puregym", category: "Gym Chains", regions: ["UK"], price: 21.99, hq: "UK" },
  { name: "Virgin Active", slug: "virgin-active", category: "Gym Chains", regions: ["UK", "AU", "GLOBAL"], price: 65.00, hq: "UK" },
  // Phone Plans (20)
  { name: "Verizon", slug: "verizon", category: "Phone Plans", regions: ["US"], price: 80.00, hq: "US" },
  { name: "AT&T Wireless", slug: "att-wireless", category: "Phone Plans", regions: ["US"], price: 75.00, hq: "US" },
  { name: "T-Mobile", slug: "t-mobile", category: "Phone Plans", regions: ["US"], price: 70.00, hq: "US" },
  { name: "Mint Mobile", slug: "mint-mobile", category: "Phone Plans", regions: ["US"], price: 15.00, hq: "US" },
  { name: "Visible", slug: "visible", category: "Phone Plans", regions: ["US"], price: 30.00, hq: "US" },
  { name: "Google Fi", slug: "google-fi", category: "Phone Plans", regions: ["US"], price: 20.00, hq: "US" },
  { name: "Cricket Wireless", slug: "cricket-wireless", category: "Phone Plans", regions: ["US"], price: 30.00, hq: "US" },
  { name: "Metro by T-Mobile", slug: "metro-tmobile", category: "Phone Plans", regions: ["US"], price: 30.00, hq: "US" },
  { name: "Boost Mobile", slug: "boost-mobile", category: "Phone Plans", regions: ["US"], price: 25.00, hq: "US" },
  { name: "US Mobile", slug: "us-mobile", category: "Phone Plans", regions: ["US"], price: 10.00, hq: "US" },
  { name: "EE", slug: "ee-mobile", category: "Phone Plans", regions: ["UK"], price: 35.00, hq: "UK" },
  { name: "Vodafone UK", slug: "vodafone-uk", category: "Phone Plans", regions: ["UK"], price: 30.00, hq: "UK" },
  { name: "Three UK", slug: "three-uk", category: "Phone Plans", regions: ["UK"], price: 25.00, hq: "UK" },
  { name: "O2 UK", slug: "o2-uk", category: "Phone Plans", regions: ["UK"], price: 28.00, hq: "UK" },
  { name: "Telstra", slug: "telstra", category: "Phone Plans", regions: ["AU"], price: 65.00, hq: "Australia" },
  { name: "Optus", slug: "optus", category: "Phone Plans", regions: ["AU"], price: 55.00, hq: "Australia" },
  { name: "Vodafone AU", slug: "vodafone-au", category: "Phone Plans", regions: ["AU"], price: 50.00, hq: "Australia" },
  { name: "Rogers", slug: "rogers", category: "Phone Plans", regions: ["CANADA"], price: 75.00, hq: "Canada" },
  { name: "Bell Canada", slug: "bell-canada", category: "Phone Plans", regions: ["CANADA"], price: 70.00, hq: "Canada" },
  { name: "Telus", slug: "telus", category: "Phone Plans", regions: ["CANADA"], price: 65.00, hq: "Canada" },
  // ISP (15)
  { name: "Comcast Xfinity", slug: "comcast-xfinity", category: "ISP", regions: ["US"], price: 75.00, hq: "US" },
  { name: "Spectrum Internet", slug: "spectrum-internet", category: "ISP", regions: ["US"], price: 49.99, hq: "US" },
  { name: "AT&T Internet", slug: "att-internet", category: "ISP", regions: ["US"], price: 55.00, hq: "US" },
  { name: "Verizon Fios", slug: "verizon-fios", category: "ISP", regions: ["US"], price: 49.99, hq: "US" },
  { name: "Cox Internet", slug: "cox-internet", category: "ISP", regions: ["US"], price: 49.99, hq: "US" },
  { name: "CenturyLink", slug: "centurylink", category: "ISP", regions: ["US"], price: 50.00, hq: "US" },
  { name: "Frontier", slug: "frontier-internet", category: "ISP", regions: ["US"], price: 49.99, hq: "US" },
  { name: "Starlink", slug: "starlink", category: "ISP", regions: ["GLOBAL"], price: 120.00, hq: "US" },
  { name: "BT Broadband", slug: "bt-broadband", category: "ISP", regions: ["UK"], price: 32.99, hq: "UK" },
  { name: "Virgin Media", slug: "virgin-media", category: "ISP", regions: ["UK"], price: 44.00, hq: "UK" },
  { name: "Sky Broadband", slug: "sky-broadband", category: "ISP", regions: ["UK"], price: 28.00, hq: "UK" },
  { name: "TalkTalk", slug: "talktalk", category: "ISP", regions: ["UK"], price: 24.00, hq: "UK" },
  { name: "NBN Australia", slug: "nbn-australia", category: "ISP", regions: ["AU"], price: 69.00, hq: "Australia" },
  { name: "Deutsche Telekom", slug: "deutsche-telekom", category: "ISP", regions: ["GERMANY"], price: 39.95, hq: "Germany" },
  { name: "Orange France", slug: "orange-france", category: "ISP", regions: ["FRANCE"], price: 29.99, hq: "France" },
  // Health/Wellness (12)
  { name: "Noom", slug: "noom", category: "Health/Wellness", regions: ["GLOBAL"], price: 59.00, hq: "US" },
  { name: "WW (Weight Watchers)", slug: "weight-watchers", category: "Health/Wellness", regions: ["GLOBAL"], price: 22.95, hq: "US" },
  { name: "MyFitnessPal Premium", slug: "myfitnesspal-premium", category: "Health/Wellness", regions: ["GLOBAL"], price: 19.99, hq: "US" },
  { name: "Fitbit Premium", slug: "fitbit-premium", category: "Health/Wellness", regions: ["GLOBAL"], price: 9.99, hq: "US" },
  { name: "Apple Fitness+", slug: "apple-fitness-plus", category: "Health/Wellness", regions: ["GLOBAL"], price: 9.99, hq: "US" },
  { name: "Whoop", slug: "whoop", category: "Health/Wellness", regions: ["GLOBAL"], price: 30.00, hq: "US" },
  { name: "Oura Ring", slug: "oura-ring", category: "Health/Wellness", regions: ["GLOBAL"], price: 5.99, hq: "Finland" },
  { name: "8fit", slug: "8fit", category: "Health/Wellness", regions: ["GLOBAL"], price: 19.99, hq: "Germany" },
  { name: "Centr", slug: "centr", category: "Health/Wellness", regions: ["GLOBAL"], price: 19.99, hq: "US" },
  { name: "Obe Fitness", slug: "obe-fitness", category: "Health/Wellness", regions: ["GLOBAL"], price: 27.99, hq: "US" },
  { name: "Beachbody", slug: "beachbody", category: "Health/Wellness", regions: ["US", "UK", "CANADA"], price: 39.99, hq: "US" },
  { name: "Daily Burn", slug: "daily-burn", category: "Health/Wellness", regions: ["GLOBAL"], price: 26.99, hq: "US" },
  // Streaming (15)
  { name: "Paramount+", slug: "paramount-plus", category: "Streaming", regions: ["US", "UK", "AU", "CANADA"], price: 5.99, hq: "US" },
  { name: "Peacock Premium", slug: "peacock-premium", category: "Streaming", regions: ["US"], price: 5.99, hq: "US" },
  { name: "Discovery+", slug: "discovery-plus", category: "Streaming", regions: ["US", "UK", "EU"], price: 4.99, hq: "US" },
  { name: "BritBox", slug: "britbox", category: "Streaming", regions: ["US", "UK", "AU", "CANADA"], price: 7.99, hq: "UK" },
  { name: "Shudder", slug: "shudder", category: "Streaming", regions: ["US", "UK", "AU", "CANADA"], price: 5.99, hq: "US" },
  { name: "AMC+", slug: "amc-plus", category: "Streaming", regions: ["US"], price: 8.99, hq: "US" },
  { name: "Starz", slug: "starz", category: "Streaming", regions: ["US"], price: 9.99, hq: "US" },
  { name: "MUBI", slug: "mubi", category: "Streaming", regions: ["GLOBAL"], price: 12.99, hq: "UK" },
  { name: "Crunchyroll", slug: "crunchyroll", category: "Streaming", regions: ["GLOBAL"], price: 7.99, hq: "US" },
  { name: "Funimation", slug: "funimation", category: "Streaming", regions: ["US", "UK", "AU"], price: 5.99, hq: "US" },
  { name: "CuriosityStream", slug: "curiositystream", category: "Streaming", regions: ["GLOBAL"], price: 4.99, hq: "US" },
  { name: "Kanopy", slug: "kanopy", category: "Streaming", regions: ["GLOBAL"], price: 0, hq: "US" },
  { name: "Acorn TV", slug: "acorn-tv", category: "Streaming", regions: ["GLOBAL"], price: 6.99, hq: "US" },
  { name: "Hallmark Movies Now", slug: "hallmark-movies-now", category: "Streaming", regions: ["US"], price: 5.99, hq: "US" },
  { name: "Philo", slug: "philo", category: "Streaming", regions: ["US"], price: 25.00, hq: "US" },
  // E-commerce (10)
  { name: "Amazon Prime", slug: "amazon-prime", category: "E-commerce", regions: ["GLOBAL"], price: 14.99, hq: "US" },
  { name: "Walmart+", slug: "walmart-plus", category: "E-commerce", regions: ["US"], price: 12.95, hq: "US" },
  { name: "Instacart+", slug: "instacart-plus", category: "E-commerce", regions: ["US", "CANADA"], price: 9.99, hq: "US" },
  { name: "Costco", slug: "costco", category: "E-commerce", regions: ["US", "UK", "CANADA", "AU"], price: 5.00, hq: "US" },
  { name: "Sam's Club", slug: "sams-club", category: "E-commerce", regions: ["US"], price: 4.17, hq: "US" },
  { name: "Thrive Market", slug: "thrive-market", category: "E-commerce", regions: ["US"], price: 5.00, hq: "US" },
  { name: "FabFitFun", slug: "fabfitfun", category: "E-commerce", regions: ["US", "CANADA"], price: 54.99, hq: "US" },
  { name: "Stitch Fix", slug: "stitch-fix", category: "E-commerce", regions: ["US", "UK"], price: 20.00, hq: "US" },
  { name: "Rent the Runway", slug: "rent-the-runway", category: "E-commerce", regions: ["US"], price: 89.00, hq: "US" },
  { name: "Birchbox", slug: "birchbox", category: "E-commerce", regions: ["US"], price: 15.00, hq: "US" },
  // Travel (10)
  { name: "Tripadvisor Plus", slug: "tripadvisor-plus", category: "Travel", regions: ["GLOBAL"], price: 8.25, hq: "US" },
  { name: "Scott's Cheap Flights", slug: "scotts-cheap-flights", category: "Travel", regions: ["GLOBAL"], price: 49.00, hq: "US" },
  { name: "Global Entry", slug: "global-entry", category: "Travel", regions: ["US"], price: 8.33, hq: "US" },
  { name: "Priority Pass", slug: "priority-pass", category: "Travel", regions: ["GLOBAL"], price: 69.00, hq: "UK" },
  { name: "LoungeBuddy", slug: "loungebuddy", category: "Travel", regions: ["GLOBAL"], price: 0, hq: "US" },
  { name: "Airbnb Plus Host", slug: "airbnb-plus-host", category: "Travel", regions: ["GLOBAL"], price: 0, hq: "US" },
  { name: "CLEAR", slug: "clear-travel", category: "Travel", regions: ["US"], price: 15.42, hq: "US" },
  { name: "AAA Membership", slug: "aaa-membership", category: "Travel", regions: ["US"], price: 5.67, hq: "US" },
  { name: "Roadside Assist AU", slug: "roadside-assist-au", category: "Travel", regions: ["AU"], price: 12.50, hq: "Australia" },
  { name: "RAC UK", slug: "rac-uk", category: "Travel", regions: ["UK"], price: 7.50, hq: "UK" },
  // Fitness App (12)
  { name: "Strava Premium", slug: "strava-premium", category: "Fitness App", regions: ["GLOBAL"], price: 11.99, hq: "US" },
  { name: "Nike Training Club", slug: "nike-training-club", category: "Fitness App", regions: ["GLOBAL"], price: 0, hq: "US" },
  { name: "SWEAT", slug: "sweat-app", category: "Fitness App", regions: ["GLOBAL"], price: 19.99, hq: "Australia" },
  { name: "Alo Moves", slug: "alo-moves", category: "Fitness App", regions: ["GLOBAL"], price: 14.00, hq: "US" },
  { name: "Freeletics", slug: "freeletics", category: "Fitness App", regions: ["GLOBAL"], price: 8.33, hq: "Germany" },
  { name: "Zwift", slug: "zwift", category: "Fitness App", regions: ["GLOBAL"], price: 14.99, hq: "US" },
  { name: "TrainerRoad", slug: "trainerroad", category: "Fitness App", regions: ["GLOBAL"], price: 19.95, hq: "US" },
  { name: "Fitbod", slug: "fitbod", category: "Fitness App", regions: ["GLOBAL"], price: 12.99, hq: "US" },
  { name: "JEFIT", slug: "jefit", category: "Fitness App", regions: ["GLOBAL"], price: 6.99, hq: "US" },
  { name: "Strong App", slug: "strong-app", category: "Fitness App", regions: ["GLOBAL"], price: 4.99, hq: "US" },
  { name: "Map My Run", slug: "map-my-run", category: "Fitness App", regions: ["GLOBAL"], price: 5.99, hq: "US" },
  { name: "Runkeeper Go", slug: "runkeeper-go", category: "Fitness App", regions: ["GLOBAL"], price: 9.99, hq: "US" },
];

function genSteps(method: string) {
  const s: Record<string, { step: number; instruction: string }[]> = {
    "online": [
      { step: 1, instruction: "Log into your account on the website" },
      { step: 2, instruction: "Navigate to Account Settings or Subscription" },
      { step: 3, instruction: "Look for Cancel or Manage Subscription option" },
      { step: 4, instruction: "Follow the cancellation prompts and confirm" },
    ],
    "phone": [
      { step: 1, instruction: "Call customer service during business hours" },
      { step: 2, instruction: "Navigate the phone menu to reach cancellation department" },
      { step: 3, instruction: "Be prepared to decline retention offers" },
      { step: 4, instruction: "Request confirmation email or reference number" },
    ],
    "mail": [
      { step: 1, instruction: "Write a formal cancellation letter with your account details" },
      { step: 2, instruction: "Send via certified mail with return receipt" },
      { step: 3, instruction: "Keep copies of all correspondence" },
      { step: 4, instruction: "Follow up if no confirmation within 2 weeks" },
    ],
    "in-person": [
      { step: 1, instruction: "Visit your local branch or store" },
      { step: 2, instruction: "Bring ID and account information" },
      { step: 3, instruction: "Request to speak with a manager if needed" },
      { step: 4, instruction: "Get written confirmation of cancellation" },
    ],
    "store": [
      { step: 1, instruction: "Visit an authorized retail location" },
      { step: 2, instruction: "Bring your account details and ID" },
      { step: 3, instruction: "Request cancellation from a representative" },
      { step: 4, instruction: "Obtain written confirmation before leaving" },
    ],
  };
  return s[method] || s["online"];
}

async function main() {
  console.log("Seeding " + companies.length + " additional companies...");
  let seeded = 0;
  for (const co of companies) {
    const t = tpl[co.category] || tpl["Marketing Tools"];
    const method = t.methods[Math.floor(Math.random() * t.methods.length)];
    const patterns = t.patterns[Math.floor(Math.random() * t.patterns.length)];
    const diff = t.diff[0] + Math.random() * (t.diff[1] - t.diff[0]);
    const dark = t.dark[0] + Math.random() * (t.dark[1] - t.dark[0]);
    const data = {
      name: co.name, slug: co.slug, category: co.category, regions: co.regions,
      avgMonthlyPrice: co.price, yearlyPrice: co.price * 12 * 0.85,
      difficultyScore: Math.round(diff * 10) / 10,
      darkPatternScore: Math.round(dark * 10) / 10,
      clicksToCancel: method === "online" ? Math.floor(Math.random() * 5) + 3 : 0,
      estimatedCancelTime: method === "phone" ? Math.floor(Math.random() * 30) + 15 : Math.floor(Math.random() * 10) + 3,
      cancellationMethod: method,
      cancellationSteps: genSteps(method),
      freeTierAvailable: Math.random() > 0.7,
      headquarters: co.hq,
      darkPatterns: JSON.stringify(patterns),
      alternatives: JSON.stringify([]),
      totalCancellations: Math.floor(Math.random() * 50000) + 1000,
      verificationStatus: "verified",
      communityScore: Math.round(Math.random() * 50) / 10,
      successRate: Math.round((70 + Math.random() * 25) * 10) / 10,
    };
    try {
      await prisma.saasCompany.upsert({ where: { slug: co.slug }, update: data, create: data });
      seeded++;
    } catch { console.log("Skip: " + co.name); }
  }
  console.log("Done! Seeded " + seeded + " companies.");
}

main().catch((e) => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
