import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const companies = [
  // STREAMING (20 companies)
  {
    name: "Netflix",
    slug: "netflix",
    category: "Streaming",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 15.49,
    yearlyPrice: 185.88,
    difficultyScore: 1.5,
    darkPatternScore: 1.5,
    clicksToCancel: 3,
    estimatedCancelTime: 2,
    cancellationUrl: "https://www.netflix.com/cancelplan",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Confirmshaming"],
    alternatives: [{ name: "Tubi", price: 0 }, { name: "Pluto TV", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to netflix.com/cancelplan or Account > Cancel Membership" },
      { step: 2, instruction: "Click 'Finish Cancellation'" },
      { step: 3, instruction: "Your account stays active until the end of the billing period" },
    ],
  },
  {
    name: "Disney+",
    slug: "disney-plus",
    category: "Streaming",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 13.99,
    yearlyPrice: 139.99,
    difficultyScore: 1.3,
    darkPatternScore: 1.5,
    clicksToCancel: 3,
    estimatedCancelTime: 2,
    cancellationUrl: "https://www.disneyplus.com/account",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Confirmshaming"],
    alternatives: [{ name: "Tubi", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to disneyplus.com/account" },
      { step: 2, instruction: "Click your subscription" },
      { step: 3, instruction: "Select 'Cancel Subscription'" },
    ],
  },
  {
    name: "Hulu",
    slug: "hulu",
    category: "Streaming",
    regions: ["US"],
    avgMonthlyPrice: 17.99,
    yearlyPrice: 215.88,
    difficultyScore: 1.8,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://secure.hulu.com/account",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Confirmshaming", "Retention offers"],
    alternatives: [{ name: "Peacock Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to secure.hulu.com/account" },
      { step: 2, instruction: "Click 'Cancel' under Your Subscription" },
      { step: 3, instruction: "Select a reason and confirm" },
    ],
  },
  {
    name: "HBO Max",
    slug: "hbo-max",
    category: "Streaming",
    regions: ["US", "EU"],
    avgMonthlyPrice: 15.99,
    yearlyPrice: 149.99,
    difficultyScore: 1.5,
    darkPatternScore: 2.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://www.max.com/account",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Confirmshaming"],
    alternatives: [{ name: "Tubi", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open the Max app or go to max.com" },
      { step: 2, instruction: "Go to Settings > Subscription" },
      { step: 3, instruction: "Select 'Cancel Subscription'" },
    ],
  },
  {
    name: "YouTube Premium",
    slug: "youtube-premium",
    category: "Streaming",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 13.99,
    yearlyPrice: 167.88,
    difficultyScore: 1.5,
    darkPatternScore: 2.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://www.youtube.com/paid_memberships",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Confirmshaming"],
    alternatives: [{ name: "YouTube Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to youtube.com/paid_memberships" },
      { step: 2, instruction: "Click 'Manage membership'" },
      { step: 3, instruction: "Click 'Deactivate' or 'Cancel'" },
    ],
  },
  {
    name: "Apple TV+",
    slug: "apple-tv-plus",
    category: "Streaming",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 9.99,
    yearlyPrice: 99.00,
    difficultyScore: 1.5,
    darkPatternScore: 1.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: [],
    alternatives: [{ name: "Tubi", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "On iPhone: Settings > Apple ID > Subscriptions" },
      { step: 2, instruction: "Find Apple TV+ and tap Cancel" },
      { step: 3, instruction: "On web: tv.apple.com > Account > Manage Subscriptions" },
    ],
  },
  {
    name: "Peacock",
    slug: "peacock",
    category: "Streaming",
    regions: ["US"],
    avgMonthlyPrice: 7.99,
    yearlyPrice: 79.99,
    difficultyScore: 1.5,
    darkPatternScore: 2.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://www.peacocktv.com/account/plans",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Confirmshaming"],
    alternatives: [{ name: "Peacock Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to peacocktv.com/account" },
      { step: 2, instruction: "Click Plans and Payment" },
      { step: 3, instruction: "Select Cancel Plan" },
    ],
  },
  {
    name: "Paramount+",
    slug: "paramount-plus",
    category: "Streaming",
    regions: ["US", "UK", "AU"],
    avgMonthlyPrice: 11.99,
    yearlyPrice: 119.99,
    difficultyScore: 1.5,
    darkPatternScore: 2.0,
    clicksToCancel: 3,
    estimatedCancelTime: 2,
    cancellationUrl: "https://www.paramountplus.com/account",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Confirmshaming"],
    alternatives: [{ name: "Pluto TV", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to paramountplus.com/account" },
      { step: 2, instruction: "Click Cancel Subscription" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "Amazon Prime Video",
    slug: "amazon-prime-video",
    category: "Streaming",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 8.99,
    yearlyPrice: 107.88,
    difficultyScore: 3.5,
    darkPatternScore: 7.5,
    clicksToCancel: 6,
    estimatedCancelTime: 10,
    cancellationUrl: "https://www.amazon.com/mc/pipelines/cancel-prime",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Confirmshaming", "Misdirection", "Obstruction", "Visual interference", "Roach motel"],
    alternatives: [{ name: "Tubi", price: 0 }],
    knownLawsuits: "FTC lawsuit 2023 - Project Iliad dark pattern case",
    cancellationSteps: [
      { step: 1, instruction: "Go to amazon.com > Account > Prime Membership" },
      { step: 2, instruction: "Click 'End Membership'" },
      { step: 3, instruction: "Navigate through 6+ reminder screens about benefits" },
      { step: 4, instruction: "Choose end date" },
      { step: 5, instruction: "Confirm cancellation" },
    ],
  },
  {
    name: "Crunchyroll",
    slug: "crunchyroll",
    category: "Streaming",
    regions: ["US", "UK", "EU", "AU", "GLOBAL"],
    avgMonthlyPrice: 7.99,
    yearlyPrice: 79.99,
    difficultyScore: 2.0,
    darkPatternScore: 2.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://www.crunchyroll.com/account",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Crunchyroll Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to crunchyroll.com/account" },
      { step: 2, instruction: "Click on your subscription" },
      { step: 3, instruction: "Select Cancel" },
    ],
  },
  {
    name: "Discovery+",
    slug: "discovery-plus",
    category: "Streaming",
    regions: ["US", "UK", "EU", "INDIA"],
    avgMonthlyPrice: 8.99,
    yearlyPrice: 83.99,
    difficultyScore: 2.0,
    darkPatternScore: 2.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://www.discoveryplus.com/account",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Confirmshaming"],
    alternatives: [{ name: "Tubi", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to discoveryplus.com/account" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "DAZN",
    slug: "dazn",
    category: "Streaming",
    regions: ["US", "UK", "EU", "CANADA", "GLOBAL"],
    avgMonthlyPrice: 19.99,
    yearlyPrice: 149.99,
    difficultyScore: 2.5,
    darkPatternScore: 3.5,
    clicksToCancel: 4,
    estimatedCancelTime: 4,
    cancellationUrl: "https://www.dazn.com/account",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "UK",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Free-to-air sports", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to dazn.com/account" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "Twitch Turbo",
    slug: "twitch-turbo",
    category: "Streaming",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 11.99,
    yearlyPrice: 143.88,
    difficultyScore: 2.0,
    darkPatternScore: 2.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://www.twitch.tv/subscriptions",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Twitch Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to twitch.tv > Settings > Subscriptions" },
      { step: 2, instruction: "Find Twitch Turbo" },
      { step: 3, instruction: "Click Cancel" },
    ],
  },
  // INDIA-SPECIFIC STREAMING
  {
    name: "Hotstar Premium",
    slug: "hotstar-premium",
    category: "Streaming",
    regions: ["INDIA"],
    avgMonthlyPrice: 4.99,
    yearlyPrice: 49.99,
    difficultyScore: 2.5,
    darkPatternScore: 4.0,
    clicksToCancel: 4,
    estimatedCancelTime: 4,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "India",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "Hotstar Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open Hotstar app or website" },
      { step: 2, instruction: "Go to Account > Subscription" },
      { step: 3, instruction: "Select Cancel subscription" },
    ],
  },
  {
    name: "Zee5 Premium",
    slug: "zee5-premium",
    category: "Streaming",
    regions: ["INDIA", "UK", "US"],
    avgMonthlyPrice: 2.99,
    yearlyPrice: 29.99,
    difficultyScore: 2.5,
    darkPatternScore: 4.0,
    clicksToCancel: 4,
    estimatedCancelTime: 4,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "India",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Zee5 Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open Zee5 app or website" },
      { step: 2, instruction: "Go to Account > Subscription" },
      { step: 3, instruction: "Select Cancel subscription" },
    ],
  },
  {
    name: "SonyLIV Premium",
    slug: "sonyliv-premium",
    category: "Streaming",
    regions: ["INDIA"],
    avgMonthlyPrice: 3.99,
    yearlyPrice: 39.99,
    difficultyScore: 2.5,
    darkPatternScore: 4.0,
    clicksToCancel: 4,
    estimatedCancelTime: 4,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "India",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "SonyLIV Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open SonyLIV app or website" },
      { step: 2, instruction: "Go to Account > Subscription" },
      { step: 3, instruction: "Select Cancel subscription" },
    ],
  },
  // UK-SPECIFIC STREAMING
  {
    name: "NOW TV",
    slug: "now-tv",
    category: "Streaming",
    regions: ["UK"],
    avgMonthlyPrice: 9.99,
    yearlyPrice: 119.88,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://www.nowtv.com/account",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "UK",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Freeview", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to nowtv.com/account" },
      { step: 2, instruction: "Select your pass" },
      { step: 3, instruction: "Click Cancel" },
    ],
  },
  {
    name: "BT Sport",
    slug: "bt-sport",
    category: "Streaming",
    regions: ["UK"],
    avgMonthlyPrice: 25.00,
    yearlyPrice: 300.00,
    difficultyScore: 3.5,
    darkPatternScore: 5.0,
    clicksToCancel: 0,
    estimatedCancelTime: 20,
    cancellationPhone: "0800 800 150",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "UK",
    darkPatterns: ["Phone-only cancellation", "Retention offers"],
    alternatives: [{ name: "Free-to-air sports", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 0800 800 150" },
      { step: 2, instruction: "Request cancellation" },
      { step: 3, instruction: "Navigate retention offers" },
    ],
  },
  // AUSTRALIA-SPECIFIC STREAMING
  {
    name: "Stan",
    slug: "stan",
    category: "Streaming",
    regions: ["AU"],
    avgMonthlyPrice: 12.00,
    yearlyPrice: 144.00,
    difficultyScore: 1.5,
    darkPatternScore: 2.0,
    clicksToCancel: 3,
    estimatedCancelTime: 2,
    cancellationUrl: "https://www.stan.com.au/account",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "AU",
    darkPatterns: ["Confirmshaming"],
    alternatives: [{ name: "ABC iview", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to stan.com.au/account" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "Foxtel Now",
    slug: "foxtel-now",
    category: "Streaming",
    regions: ["AU"],
    avgMonthlyPrice: 25.00,
    yearlyPrice: 300.00,
    difficultyScore: 3.0,
    darkPatternScore: 4.5,
    clicksToCancel: 5,
    estimatedCancelTime: 5,
    cancellationUrl: "https://www.foxtel.com.au/now/myaccount",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "AU",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "ABC iview", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to foxtel.com.au/now/myaccount" },
      { step: 2, instruction: "Select Manage subscription" },
      { step: 3, instruction: "Click Cancel" },
    ],
  },
  {
    name: "Kayo Sports",
    slug: "kayo-sports",
    category: "Streaming",
    regions: ["AU"],
    avgMonthlyPrice: 25.00,
    yearlyPrice: 300.00,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://www.kayosports.com.au/account",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "AU",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Free-to-air sports", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to kayosports.com.au/account" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  // SOUTH KOREA STREAMING
  {
    name: "Wavve",
    slug: "wavve",
    category: "Streaming",
    regions: ["SOUTH_KOREA"],
    avgMonthlyPrice: 7.99,
    yearlyPrice: 79.99,
    difficultyScore: 2.5,
    darkPatternScore: 4.0,
    clicksToCancel: 4,
    estimatedCancelTime: 4,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "South Korea",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Wavve Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open Wavve app" },
      { step: 2, instruction: "Go to Account > Subscription" },
      { step: 3, instruction: "Cancel subscription" },
    ],
  },
  {
    name: "Tving",
    slug: "tving",
    category: "Streaming",
    regions: ["SOUTH_KOREA"],
    avgMonthlyPrice: 6.99,
    yearlyPrice: 69.99,
    difficultyScore: 2.5,
    darkPatternScore: 4.0,
    clicksToCancel: 4,
    estimatedCancelTime: 4,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "South Korea",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Tving Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open Tving app" },
      { step: 2, instruction: "Go to Account > Subscription" },
      { step: 3, instruction: "Cancel subscription" },
    ],
  },
  // CANADA STREAMING
  {
    name: "Crave",
    slug: "crave",
    category: "Streaming",
    regions: ["CANADA"],
    avgMonthlyPrice: 19.99,
    yearlyPrice: 239.88,
    difficultyScore: 3.0,
    darkPatternScore: 4.0,
    clicksToCancel: 4,
    estimatedCancelTime: 5,
    cancellationPhone: "1-888-759-3474",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "Canada",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "CBC Gem Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to cravetv.ca > My Account" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Or call 1-888-759-3474" },
    ],
  },
  // FRANCE/EU STREAMING
  {
    name: "Canal+",
    slug: "canal-plus",
    category: "Streaming",
    regions: ["EU", "FRANCE"],
    avgMonthlyPrice: 19.99,
    yearlyPrice: 239.88,
    difficultyScore: 3.5,
    darkPatternScore: 5.0,
    clicksToCancel: 0,
    estimatedCancelTime: 20,
    cancellationPhone: "+33 1 71 35 35 35",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "France",
    darkPatterns: ["Phone cancellation", "Retention offers", "Notice period"],
    alternatives: [{ name: "France.tv", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Call +33 1 71 35 35 35" },
      { step: 2, instruction: "Request cancellation" },
      { step: 3, instruction: "Note: France requires max 3-click cancellation by law" },
    ],
  },

  // MUSIC (10 companies)
  {
    name: "Spotify",
    slug: "spotify",
    category: "Music",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 11.99,
    yearlyPrice: 143.88,
    difficultyScore: 3.8,
    darkPatternScore: 9.0,
    clicksToCancel: 5,
    estimatedCancelTime: 8,
    cancellationUrl: "https://www.spotify.com/account/subscription",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "Sweden",
    darkPatterns: ["Confirmshaming", "Hidden cancel button", "Roach motel", "Misdirection", "Obstruction", "Forced continuity", "Trick questions", "Visual interference", "Preselection"],
    alternatives: [{ name: "YouTube Music Free", price: 0 }, { name: "Spotify Free", price: 0 }],
    knownLawsuits: "KnownHost 2024 study: Uses 9 dark patterns, requires 5 clicks to cancel",
    cancellationSteps: [
      { step: 1, instruction: "Go to spotify.com/account/subscription" },
      { step: 2, instruction: "Click 'Change plan'" },
      { step: 3, instruction: "Navigate through multiple retention screens" },
      { step: 4, instruction: "Select 'Cancel Premium'" },
      { step: 5, instruction: "Confirm cancellation" },
    ],
  },
  {
    name: "Apple Music",
    slug: "apple-music",
    category: "Music",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 10.99,
    yearlyPrice: 109.00,
    difficultyScore: 1.5,
    darkPatternScore: 1.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: [],
    alternatives: [{ name: "Spotify Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "On iPhone: Settings > Apple ID > Subscriptions" },
      { step: 2, instruction: "Find Apple Music and tap Cancel" },
      { step: 3, instruction: "On Mac: App Store > Account > Subscriptions" },
    ],
  },
  {
    name: "Tidal",
    slug: "tidal",
    category: "Music",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 10.99,
    yearlyPrice: 119.88,
    difficultyScore: 3.5,
    darkPatternScore: 7.0,
    clicksToCancel: 4,
    estimatedCancelTime: 6,
    cancellationUrl: "https://account.tidal.com/subscription",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "Norway",
    darkPatterns: ["Confirmshaming", "Misdirection", "Obstruction", "Roach motel", "Forced continuity"],
    alternatives: [{ name: "Spotify Free", price: 0 }],
    knownLawsuits: "KnownHost 2024: Uses 7 dark patterns",
    cancellationSteps: [
      { step: 1, instruction: "Go to account.tidal.com" },
      { step: 2, instruction: "Click on Subscription" },
      { step: 3, instruction: "Select Cancel subscription" },
    ],
  },
  {
    name: "Amazon Music",
    slug: "amazon-music",
    category: "Music",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 9.99,
    yearlyPrice: 99.00,
    difficultyScore: 3.5,
    darkPatternScore: 7.0,
    clicksToCancel: 5,
    estimatedCancelTime: 8,
    cancellationUrl: "https://www.amazon.com/music/settings",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Confirmshaming", "Misdirection", "Obstruction", "Roach motel"],
    alternatives: [{ name: "Spotify Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to amazon.com/music/settings" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Navigate through multiple retention screens" },
    ],
  },
  {
    name: "JioSaavn Pro",
    slug: "jiosaavn-pro",
    category: "Music",
    regions: ["INDIA"],
    avgMonthlyPrice: 1.49,
    yearlyPrice: 11.99,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "India",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "JioSaavn Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open JioSaavn app" },
      { step: 2, instruction: "Go to Settings > Subscription" },
      { step: 3, instruction: "Cancel through app store" },
    ],
  },
  {
    name: "Gaana Plus",
    slug: "gaana-plus",
    category: "Music",
    regions: ["INDIA"],
    avgMonthlyPrice: 1.19,
    yearlyPrice: 9.99,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "India",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Gaana Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open Gaana app" },
      { step: 2, instruction: "Go to Settings > Subscription" },
      { step: 3, instruction: "Cancel through app store" },
    ],
  },
  {
    name: "Melon Music",
    slug: "melon-music",
    category: "Music",
    regions: ["SOUTH_KOREA"],
    avgMonthlyPrice: 5.99,
    yearlyPrice: 59.99,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "South Korea",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Melon Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open Melon app" },
      { step: 2, instruction: "Go to Settings > Subscription" },
      { step: 3, instruction: "Cancel subscription" },
    ],
  },

  // INTERNET/CABLE - THE WORST OFFENDERS (15 companies)
  {
    name: "Comcast/Xfinity",
    slug: "comcast-xfinity",
    category: "Internet/Cable",
    regions: ["US"],
    avgMonthlyPrice: 89.99,
    yearlyPrice: 1079.88,
    difficultyScore: 5.0,
    darkPatternScore: 9.5,
    clicksToCancel: 0,
    estimatedCancelTime: 60,
    cancellationPhone: "1-800-934-6489",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Phone-only cancellation", "Long hold times", "Aggressive retention", "Transfer maze", "Equipment return threats"],
    alternatives: [{ name: "T-Mobile Home Internet", price: 50 }],
    knownLawsuits: "Multiple FCC complaints, class action lawsuits for deceptive billing",
    cancellationSteps: [
      { step: 1, instruction: "Call 1-800-934-6489 (Xfinity customer service)" },
      { step: 2, instruction: "Navigate through the automated menu - say Cancel Service" },
      { step: 3, instruction: "Be prepared for a long hold time (15-45 minutes)" },
      { step: 4, instruction: "The retention specialist will offer discounts - stay firm" },
      { step: 5, instruction: "Request a confirmation number and email confirmation" },
      { step: 6, instruction: "Return all equipment to an Xfinity store" },
    ],
  },
  {
    name: "AT&T",
    slug: "att",
    category: "Internet/Cable",
    regions: ["US"],
    avgMonthlyPrice: 75.00,
    yearlyPrice: 900.00,
    difficultyScore: 4.8,
    darkPatternScore: 8.5,
    clicksToCancel: 0,
    estimatedCancelTime: 45,
    cancellationPhone: "1-800-288-2020",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Phone-only cancellation", "Long hold times", "Aggressive retention", "Early termination fees"],
    alternatives: [{ name: "T-Mobile Home Internet", price: 50 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 1-800-288-2020" },
      { step: 2, instruction: "Say Cancel service to the automated system" },
      { step: 3, instruction: "Wait for a retention specialist (15-30 min)" },
      { step: 4, instruction: "Decline all retention offers firmly" },
      { step: 5, instruction: "Get confirmation number and return equipment" },
    ],
  },
  {
    name: "Verizon Fios",
    slug: "verizon-fios",
    category: "Internet/Cable",
    regions: ["US"],
    avgMonthlyPrice: 79.99,
    yearlyPrice: 959.88,
    difficultyScore: 4.5,
    darkPatternScore: 7.5,
    clicksToCancel: 0,
    estimatedCancelTime: 40,
    cancellationPhone: "1-800-837-4966",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Phone-only cancellation", "Retention offers", "Early termination fees"],
    alternatives: [{ name: "T-Mobile Home Internet", price: 50 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 1-800-837-4966" },
      { step: 2, instruction: "Request to cancel service" },
      { step: 3, instruction: "Navigate retention offers" },
      { step: 4, instruction: "Get confirmation and return equipment" },
    ],
  },
  {
    name: "Spectrum",
    slug: "spectrum",
    category: "Internet/Cable",
    regions: ["US"],
    avgMonthlyPrice: 79.99,
    yearlyPrice: 959.88,
    difficultyScore: 4.5,
    darkPatternScore: 7.5,
    clicksToCancel: 0,
    estimatedCancelTime: 45,
    cancellationPhone: "1-833-267-6094",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Phone-only cancellation", "Retention offers", "Equipment return"],
    alternatives: [{ name: "T-Mobile Home Internet", price: 50 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 1-833-267-6094" },
      { step: 2, instruction: "Request cancellation" },
      { step: 3, instruction: "Return equipment to local store" },
    ],
  },
  {
    name: "Cox Internet",
    slug: "cox-internet",
    category: "Internet/Cable",
    regions: ["US"],
    avgMonthlyPrice: 79.99,
    yearlyPrice: 959.88,
    difficultyScore: 4.3,
    darkPatternScore: 7.0,
    clicksToCancel: 0,
    estimatedCancelTime: 40,
    cancellationPhone: "1-800-234-3993",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Phone-only cancellation", "Retention offers"],
    alternatives: [{ name: "T-Mobile Home Internet", price: 50 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 1-800-234-3993" },
      { step: 2, instruction: "Request cancellation" },
      { step: 3, instruction: "Return equipment" },
    ],
  },
  {
    name: "T-Mobile",
    slug: "t-mobile",
    category: "Internet/Cable",
    regions: ["US"],
    avgMonthlyPrice: 70.00,
    yearlyPrice: 840.00,
    difficultyScore: 4.0,
    darkPatternScore: 7.0,
    clicksToCancel: 0,
    estimatedCancelTime: 30,
    cancellationPhone: "1-800-937-8997",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Phone-only cancellation", "Retention offers", "Long hold times"],
    alternatives: [{ name: "Mint Mobile", price: 15 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 1-800-937-8997" },
      { step: 2, instruction: "Request cancellation" },
      { step: 3, instruction: "Navigate retention offers" },
      { step: 4, instruction: "Get confirmation number" },
    ],
  },
  {
    name: "SiriusXM",
    slug: "siriusxm",
    category: "Entertainment",
    regions: ["US", "CANADA"],
    avgMonthlyPrice: 16.99,
    yearlyPrice: 203.88,
    difficultyScore: 4.5,
    darkPatternScore: 8.0,
    clicksToCancel: 0,
    estimatedCancelTime: 30,
    cancellationPhone: "1-866-635-2349",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Phone-only cancellation", "Aggressive retention", "Discount offers", "Long hold times"],
    alternatives: [{ name: "Spotify Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "You MUST call 1-866-635-2349 to cancel" },
      { step: 2, instruction: "Online cancellation is not available" },
      { step: 3, instruction: "Expect strong retention offers and long hold times" },
      { step: 4, instruction: "Stay firm and request cancellation confirmation" },
    ],
  },
  {
    name: "Sky TV",
    slug: "sky-tv",
    category: "Internet/Cable",
    regions: ["UK", "EU"],
    avgMonthlyPrice: 35.00,
    yearlyPrice: 420.00,
    difficultyScore: 4.0,
    darkPatternScore: 6.5,
    clicksToCancel: 0,
    estimatedCancelTime: 30,
    cancellationPhone: "0333 759 1018",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "UK",
    darkPatterns: ["Phone-only cancellation", "Retention offers", "31-day notice period"],
    alternatives: [{ name: "Freeview", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 0333 759 1018" },
      { step: 2, instruction: "Request cancellation" },
      { step: 3, instruction: "31-day notice period applies" },
      { step: 4, instruction: "Return equipment to avoid charges" },
    ],
  },
  {
    name: "Vodafone UK",
    slug: "vodafone-uk",
    category: "Internet/Cable",
    regions: ["UK"],
    avgMonthlyPrice: 30.00,
    yearlyPrice: 360.00,
    difficultyScore: 3.5,
    darkPatternScore: 5.0,
    clicksToCancel: 0,
    estimatedCancelTime: 20,
    cancellationPhone: "0333 304 0191",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "UK",
    darkPatterns: ["Phone cancellation", "Retention offers", "30-day notice"],
    alternatives: [{ name: "Giffgaff", price: 10 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 0333 304 0191" },
      { step: 2, instruction: "Request cancellation" },
      { step: 3, instruction: "30-day notice period applies" },
    ],
  },
  {
    name: "Telstra",
    slug: "telstra",
    category: "Internet/Cable",
    regions: ["AU"],
    avgMonthlyPrice: 65.00,
    yearlyPrice: 780.00,
    difficultyScore: 3.5,
    darkPatternScore: 5.0,
    clicksToCancel: 0,
    estimatedCancelTime: 25,
    cancellationPhone: "13 22 00",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "AU",
    darkPatterns: ["Phone cancellation", "Retention offers"],
    alternatives: [{ name: "Optus", price: 60 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 13 22 00" },
      { step: 2, instruction: "Request cancellation" },
      { step: 3, instruction: "Navigate retention offers" },
    ],
  },
  {
    name: "Jio Fiber",
    slug: "jio-fiber",
    category: "Internet/Cable",
    regions: ["INDIA"],
    avgMonthlyPrice: 6.99,
    yearlyPrice: 83.88,
    difficultyScore: 3.0,
    darkPatternScore: 4.0,
    clicksToCancel: 0,
    estimatedCancelTime: 15,
    cancellationPhone: "198",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "India",
    darkPatterns: ["Phone cancellation", "Retention offers"],
    alternatives: [{ name: "Airtel Fiber", price: 5 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 198 from your Jio number" },
      { step: 2, instruction: "Request cancellation" },
      { step: 3, instruction: "Return equipment" },
    ],
  },
  {
    name: "Bell Canada",
    slug: "bell-canada",
    category: "Internet/Cable",
    regions: ["CANADA"],
    avgMonthlyPrice: 75.00,
    yearlyPrice: 900.00,
    difficultyScore: 4.0,
    darkPatternScore: 6.0,
    clicksToCancel: 0,
    estimatedCancelTime: 30,
    cancellationPhone: "1-866-310-2355",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "Canada",
    darkPatterns: ["Phone cancellation", "Retention offers", "Early termination fees"],
    alternatives: [{ name: "TekSavvy", price: 50 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 1-866-310-2355" },
      { step: 2, instruction: "Request cancellation" },
      { step: 3, instruction: "Navigate retention offers" },
      { step: 4, instruction: "Return equipment" },
    ],
  },

  // FITNESS (10 companies)
  {
    name: "Planet Fitness",
    slug: "planet-fitness",
    category: "Fitness",
    regions: ["US", "CANADA", "AU"],
    avgMonthlyPrice: 24.99,
    yearlyPrice: 299.88,
    difficultyScore: 4.8,
    darkPatternScore: 8.5,
    clicksToCancel: 0,
    estimatedCancelTime: 30,
    cancellationMethod: "in-person",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["In-person or certified mail only", "No online cancellation", "Buyout fees", "30-day notice"],
    alternatives: [{ name: "Home workouts", price: 0 }],
    knownLawsuits: "Multiple state AG complaints about cancellation difficulty",
    cancellationSteps: [
      { step: 1, instruction: "You MUST cancel in person at your home club or via certified mail" },
      { step: 2, instruction: "Online cancellation is NOT available" },
      { step: 3, instruction: "Visit your home club and ask for a cancellation form" },
      { step: 4, instruction: "Fill out the form and get a copy for your records" },
      { step: 5, instruction: "Alternative: Send a certified letter to your home club" },
    ],
  },
  {
    name: "LA Fitness",
    slug: "la-fitness",
    category: "Fitness",
    regions: ["US", "CANADA"],
    avgMonthlyPrice: 34.99,
    yearlyPrice: 419.88,
    difficultyScore: 4.5,
    darkPatternScore: 7.5,
    clicksToCancel: 0,
    estimatedCancelTime: 30,
    cancellationMethod: "in-person",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["In-person or certified mail only", "30-day notice", "Buyout fees"],
    alternatives: [{ name: "Planet Fitness", price: 10 }],
    cancellationSteps: [
      { step: 1, instruction: "Visit your home gym in person" },
      { step: 2, instruction: "Request a cancellation form at the front desk" },
      { step: 3, instruction: "30 days written notice required" },
    ],
  },
  {
    name: "Anytime Fitness",
    slug: "anytime-fitness",
    category: "Fitness",
    regions: ["US", "UK", "AU", "GLOBAL"],
    avgMonthlyPrice: 41.99,
    yearlyPrice: 503.88,
    difficultyScore: 4.0,
    darkPatternScore: 6.0,
    clicksToCancel: 0,
    estimatedCancelTime: 20,
    cancellationMethod: "in-person",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["In-person cancellation", "Contract terms vary by location"],
    alternatives: [{ name: "Planet Fitness", price: 10 }],
    cancellationSteps: [
      { step: 1, instruction: "Visit your home club" },
      { step: 2, instruction: "Request cancellation form" },
      { step: 3, instruction: "Terms vary by franchise - check your contract" },
    ],
  },
  {
    name: "Golds Gym",
    slug: "golds-gym",
    category: "Fitness",
    regions: ["US", "GLOBAL"],
    avgMonthlyPrice: 34.99,
    yearlyPrice: 419.88,
    difficultyScore: 4.2,
    darkPatternScore: 6.5,
    clicksToCancel: 0,
    estimatedCancelTime: 25,
    cancellationMethod: "in-person",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["In-person cancellation", "30-day notice"],
    alternatives: [{ name: "Planet Fitness", price: 10 }],
    cancellationSteps: [
      { step: 1, instruction: "Visit your home gym in person" },
      { step: 2, instruction: "Ask for a cancellation form" },
      { step: 3, instruction: "Some locations require 30 days notice" },
    ],
  },
  {
    name: "Peloton",
    slug: "peloton",
    category: "Fitness",
    regions: ["US", "UK", "CANADA", "AU"],
    avgMonthlyPrice: 44.00,
    yearlyPrice: 528.00,
    difficultyScore: 3.0,
    darkPatternScore: 4.0,
    clicksToCancel: 5,
    estimatedCancelTime: 10,
    cancellationUrl: "https://members.onepeloton.com",
    cancellationPhone: "1-866-679-9129",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "Apple Fitness+", price: 9.99 }],
    cancellationSteps: [
      { step: 1, instruction: "Log in to members.onepeloton.com" },
      { step: 2, instruction: "Go to My Membership" },
      { step: 3, instruction: "Click Cancel membership" },
    ],
  },
  {
    name: "Apple Fitness+",
    slug: "apple-fitness-plus",
    category: "Fitness",
    regions: ["US", "UK", "EU", "AU", "CANADA"],
    avgMonthlyPrice: 9.99,
    yearlyPrice: 79.99,
    difficultyScore: 1.5,
    darkPatternScore: 1.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: [],
    alternatives: [{ name: "YouTube Fitness", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "iPhone: Settings > Apple ID > Subscriptions" },
      { step: 2, instruction: "Find Fitness+ and tap Cancel" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "Strava Premium",
    slug: "strava-premium",
    category: "Fitness",
    regions: ["US", "UK", "EU", "AU", "GLOBAL"],
    avgMonthlyPrice: 11.99,
    yearlyPrice: 79.99,
    difficultyScore: 2.0,
    darkPatternScore: 2.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://www.strava.com/settings/subscription",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Strava Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to strava.com/settings/subscription" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Confirm" },
    ],
  },

  // SOFTWARE/PRODUCTIVITY (20 companies)
  {
    name: "Adobe Creative Cloud",
    slug: "adobe-creative-cloud",
    category: "Design",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 59.99,
    yearlyPrice: 659.88,
    difficultyScore: 4.5,
    darkPatternScore: 8.5,
    clicksToCancel: 7,
    estimatedCancelTime: 15,
    cancellationUrl: "https://account.adobe.com/plans",
    cancellationPhone: "1-800-833-6687",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Early termination fee (50%)", "Multiple retention screens", "Confirmshaming", "Hidden cancel button", "Misdirection"],
    alternatives: [{ name: "Canva Free", price: 0 }, { name: "GIMP", price: 0 }, { name: "Figma Free", price: 0 }],
    knownLawsuits: "FTC investigation 2024 for hidden early termination fees",
    cancellationSteps: [
      { step: 1, instruction: "Go to account.adobe.com/plans" },
      { step: 2, instruction: "Click Manage plan next to your subscription" },
      { step: 3, instruction: "Click Cancel plan" },
      { step: 4, instruction: "Adobe will show an early termination fee (50% of remaining months)" },
      { step: 5, instruction: "Go through multiple retention screens" },
      { step: 6, instruction: "Confirm cancellation and save your confirmation email" },
    ],
  },
  {
    name: "Microsoft 365",
    slug: "microsoft-365",
    category: "Productivity",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 9.99,
    yearlyPrice: 99.99,
    difficultyScore: 2.5,
    darkPatternScore: 4.0,
    clicksToCancel: 5,
    estimatedCancelTime: 5,
    cancellationUrl: "https://account.microsoft.com/services",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "Google Docs", price: 0 }, { name: "LibreOffice", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to account.microsoft.com/services" },
      { step: 2, instruction: "Find Microsoft 365 subscription" },
      { step: 3, instruction: "Click Manage then Cancel subscription" },
    ],
  },
  {
    name: "Slack",
    slug: "slack",
    category: "Productivity",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 8.75,
    yearlyPrice: 105.00,
    difficultyScore: 2.2,
    darkPatternScore: 2.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: [],
    alternatives: [{ name: "Discord", price: 0 }, { name: "Slack Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Only workspace owners/admins can change billing" },
      { step: 2, instruction: "Go to Settings and Administration > Billing" },
      { step: 3, instruction: "Click Change plan type and select Free" },
    ],
  },
  {
    name: "Notion",
    slug: "notion",
    category: "Productivity",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 10.00,
    yearlyPrice: 96.00,
    difficultyScore: 1.5,
    darkPatternScore: 1.5,
    clicksToCancel: 3,
    estimatedCancelTime: 2,
    cancellationUrl: "https://www.notion.so/settings",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: [],
    alternatives: [{ name: "Notion Free", price: 0 }, { name: "Obsidian", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to notion.so > Settings > Billing" },
      { step: 2, instruction: "Click Downgrade to free plan" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "Zoom",
    slug: "zoom",
    category: "Productivity",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 15.99,
    yearlyPrice: 149.90,
    difficultyScore: 2.0,
    darkPatternScore: 2.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://zoom.us/account/billing",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Google Meet", price: 0 }, { name: "Zoom Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Sign in to zoom.us" },
      { step: 2, instruction: "Go to Admin > Account Management > Billing" },
      { step: 3, instruction: "Click Cancel subscription" },
    ],
  },
  {
    name: "Dropbox",
    slug: "dropbox",
    category: "Cloud Storage",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 11.99,
    yearlyPrice: 119.88,
    difficultyScore: 2.5,
    darkPatternScore: 4.0,
    clicksToCancel: 5,
    estimatedCancelTime: 5,
    cancellationUrl: "https://www.dropbox.com/account/plan",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "Google Drive", price: 0 }, { name: "Dropbox Basic", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to dropbox.com > Settings > Plan" },
      { step: 2, instruction: "Click Cancel plan or Downgrade" },
      { step: 3, instruction: "Navigate through retention screens" },
      { step: 4, instruction: "Confirm downgrade to Basic (free)" },
    ],
  },
  {
    name: "Grammarly",
    slug: "grammarly",
    category: "Productivity",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 12.00,
    yearlyPrice: 144.00,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://account.grammarly.com/subscription",
    cancellationEmail: "support@grammarly.com",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Grammarly Free", price: 0 }, { name: "LanguageTool", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Log in to account.grammarly.com" },
      { step: 2, instruction: "Go to Subscription" },
      { step: 3, instruction: "Click Cancel subscription" },
    ],
  },
  {
    name: "Canva Pro",
    slug: "canva-pro",
    category: "Design",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 14.99,
    yearlyPrice: 119.99,
    difficultyScore: 1.8,
    darkPatternScore: 2.5,
    clicksToCancel: 3,
    estimatedCancelTime: 2,
    cancellationUrl: "https://www.canva.com/settings/billing",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "AU",
    darkPatterns: ["Confirmshaming"],
    alternatives: [{ name: "Canva Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to canva.com > Settings > Billing" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "Figma",
    slug: "figma",
    category: "Design",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 15.00,
    yearlyPrice: 144.00,
    difficultyScore: 1.8,
    darkPatternScore: 2.0,
    clicksToCancel: 3,
    estimatedCancelTime: 2,
    cancellationEmail: "support@figma.com",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: [],
    alternatives: [{ name: "Figma Free", price: 0 }, { name: "Penpot", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to figma.com > Account settings > Billing" },
      { step: 2, instruction: "Click Downgrade to Starter" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "LinkedIn Premium",
    slug: "linkedin-premium",
    category: "Professional",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 29.99,
    yearlyPrice: 359.88,
    difficultyScore: 2.5,
    darkPatternScore: 4.5,
    clicksToCancel: 5,
    estimatedCancelTime: 5,
    cancellationUrl: "https://www.linkedin.com/psettings/cancel-premium",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "LinkedIn Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to linkedin.com > Settings > Manage Premium" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Navigate through retention screens" },
    ],
  },
  {
    name: "Evernote",
    slug: "evernote",
    category: "Productivity",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 14.99,
    yearlyPrice: 129.99,
    difficultyScore: 2.8,
    darkPatternScore: 4.5,
    clicksToCancel: 5,
    estimatedCancelTime: 5,
    cancellationUrl: "https://www.evernote.com/Settings.action",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "Notion Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to evernote.com > Account Settings > Billing" },
      { step: 2, instruction: "Select Downgrade to Basic" },
      { step: 3, instruction: "Navigate through retention screens" },
    ],
  },
  {
    name: "Asana Premium",
    slug: "asana-premium",
    category: "Productivity",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 13.49,
    yearlyPrice: 131.88,
    difficultyScore: 2.0,
    darkPatternScore: 2.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: [],
    alternatives: [{ name: "Asana Free", price: 0 }, { name: "Trello Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to asana.com > Admin Console > Billing" },
      { step: 2, instruction: "Click Downgrade" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "Monday.com",
    slug: "monday-com",
    category: "Productivity",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 12.00,
    yearlyPrice: 108.00,
    difficultyScore: 2.5,
    darkPatternScore: 3.0,
    clicksToCancel: 5,
    estimatedCancelTime: 5,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "Israel",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Trello Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to monday.com > Admin > Billing" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Follow prompts" },
    ],
  },
  {
    name: "Wix Premium",
    slug: "wix-premium",
    category: "Productivity",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 17.00,
    yearlyPrice: 204.00,
    difficultyScore: 3.0,
    darkPatternScore: 5.0,
    clicksToCancel: 5,
    estimatedCancelTime: 5,
    cancellationUrl: "https://www.wix.com/account/billing",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "Israel",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "Wix Free", price: 0 }, { name: "WordPress.com Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to wix.com > Account > Billing" },
      { step: 2, instruction: "Find your plan and click Cancel" },
      { step: 3, instruction: "Navigate retention screens" },
    ],
  },
  {
    name: "Squarespace",
    slug: "squarespace",
    category: "Productivity",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 16.00,
    yearlyPrice: 192.00,
    difficultyScore: 2.5,
    darkPatternScore: 3.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://account.squarespace.com/billing",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "WordPress.com Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to account.squarespace.com > Billing" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "Shopify",
    slug: "shopify",
    category: "E-commerce",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 39.00,
    yearlyPrice: 468.00,
    difficultyScore: 2.5,
    darkPatternScore: 3.5,
    clicksToCancel: 5,
    estimatedCancelTime: 5,
    cancellationUrl: "https://admin.shopify.com/store/settings",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "Canada",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "WooCommerce", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to admin.shopify.com > Settings > Plan" },
      { step: 2, instruction: "Click Deactivate store or Pause" },
      { step: 3, instruction: "Select reason and confirm" },
    ],
  },
  {
    name: "Mailchimp",
    slug: "mailchimp",
    category: "Marketing",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 13.00,
    yearlyPrice: 156.00,
    difficultyScore: 2.5,
    darkPatternScore: 3.0,
    clicksToCancel: 5,
    estimatedCancelTime: 5,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Mailchimp Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to mailchimp.com > Account > Billing" },
      { step: 2, instruction: "Click Downgrade or Cancel" },
      { step: 3, instruction: "Follow prompts" },
    ],
  },

  // SECURITY (10 companies)
  {
    name: "McAfee Antivirus",
    slug: "mcafee-antivirus",
    category: "Security",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 8.33,
    yearlyPrice: 99.99,
    difficultyScore: 4.5,
    darkPatternScore: 9.0,
    clicksToCancel: 6,
    estimatedCancelTime: 15,
    cancellationUrl: "https://home.mcafee.com/root/myaccount.aspx",
    cancellationPhone: "1-866-622-3911",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Scare tactics", "Fear-based messaging", "Hidden cancel button", "Multiple confirmation screens"],
    alternatives: [{ name: "Windows Defender", price: 0 }, { name: "Malwarebytes Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Log in to home.mcafee.com" },
      { step: 2, instruction: "Go to My Account > Subscriptions" },
      { step: 3, instruction: "Turn off Auto-Renewal" },
      { step: 4, instruction: "Navigate through scare tactics about unprotected device" },
      { step: 5, instruction: "Confirm cancellation despite pop-ups" },
    ],
  },
  {
    name: "Norton Antivirus",
    slug: "norton-antivirus",
    category: "Security",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 7.49,
    yearlyPrice: 89.99,
    difficultyScore: 4.3,
    darkPatternScore: 8.5,
    clicksToCancel: 5,
    estimatedCancelTime: 12,
    cancellationUrl: "https://manage.norton.com",
    cancellationPhone: "1-844-488-4540",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Scare tactics", "Fear-based messaging", "Retention offers", "Confirmshaming"],
    alternatives: [{ name: "Windows Defender", price: 0 }, { name: "Bitdefender Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Sign in at manage.norton.com" },
      { step: 2, instruction: "Click on your subscription" },
      { step: 3, instruction: "Turn off Auto-Renew" },
      { step: 4, instruction: "Navigate through retention/scare screens" },
    ],
  },
  {
    name: "NordVPN",
    slug: "nordvpn",
    category: "Security",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 12.99,
    yearlyPrice: 99.00,
    difficultyScore: 3.0,
    darkPatternScore: 5.0,
    clicksToCancel: 4,
    estimatedCancelTime: 5,
    cancellationEmail: "support@nordvpn.com",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "Panama",
    darkPatterns: ["Retention offers", "30-day refund window"],
    alternatives: [{ name: "ProtonVPN Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Log in to my.nordaccount.com" },
      { step: 2, instruction: "Go to Subscription > Change plan" },
      { step: 3, instruction: "Select Cancel automatic payments" },
    ],
  },
  {
    name: "ExpressVPN",
    slug: "expressvpn",
    category: "Security",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 12.95,
    yearlyPrice: 99.95,
    difficultyScore: 2.5,
    darkPatternScore: 3.5,
    clicksToCancel: 4,
    estimatedCancelTime: 4,
    cancellationEmail: "support@expressvpn.com",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "British Virgin Islands",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "ProtonVPN Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Log in to your ExpressVPN account" },
      { step: 2, instruction: "Go to Subscription settings" },
      { step: 3, instruction: "Turn off auto-renewal" },
    ],
  },
  {
    name: "Surfshark VPN",
    slug: "surfshark-vpn",
    category: "Security",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 12.95,
    yearlyPrice: 47.88,
    difficultyScore: 2.5,
    darkPatternScore: 3.5,
    clicksToCancel: 4,
    estimatedCancelTime: 4,
    cancellationEmail: "support@surfshark.com",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "Netherlands",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "ProtonVPN Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Log in to my.surfshark.com" },
      { step: 2, instruction: "Go to Subscription" },
      { step: 3, instruction: "Select Cancel auto-renewal" },
    ],
  },
  {
    name: "Dashlane",
    slug: "dashlane",
    category: "Security",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 4.99,
    yearlyPrice: 59.88,
    difficultyScore: 2.0,
    darkPatternScore: 2.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://app.dashlane.com/settings/subscription",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Bitwarden Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to app.dashlane.com > Settings > Subscription" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Export your passwords first!" },
    ],
  },
  {
    name: "1Password",
    slug: "1password",
    category: "Security",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 2.99,
    yearlyPrice: 35.88,
    difficultyScore: 2.0,
    darkPatternScore: 2.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://my.1password.com/settings/billing",
    cancellationEmail: "support@1password.com",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "Canada",
    darkPatterns: [],
    alternatives: [{ name: "Bitwarden Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to my.1password.com > Settings > Billing" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Export your passwords first!" },
    ],
  },
  {
    name: "ADT Security",
    slug: "adt-security",
    category: "Security",
    regions: ["US"],
    avgMonthlyPrice: 28.99,
    yearlyPrice: 347.88,
    difficultyScore: 4.8,
    darkPatternScore: 8.0,
    clicksToCancel: 0,
    estimatedCancelTime: 45,
    cancellationPhone: "1-800-238-2727",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Phone-only cancellation", "Early termination fee (75% remaining)", "Aggressive retention"],
    alternatives: [{ name: "Ring (no monthly required)", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 1-800-238-2727" },
      { step: 2, instruction: "Request cancellation" },
      { step: 3, instruction: "WARNING: Early termination fee is 75% of remaining contract" },
      { step: 4, instruction: "Get written confirmation" },
    ],
  },

  // NEWS/MEDIA (8 companies)
  {
    name: "NYT Digital",
    slug: "nyt-digital",
    category: "News",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 17.00,
    yearlyPrice: 204.00,
    difficultyScore: 4.0,
    darkPatternScore: 6.0,
    clicksToCancel: 0,
    estimatedCancelTime: 15,
    cancellationPhone: "1-800-591-9233",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Phone-only cancellation", "Aggressive retention", "Discount offers"],
    alternatives: [{ name: "Apple News+", price: 12.99 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 1-800-591-9233 to cancel" },
      { step: 2, instruction: "Chat support may also work - try live chat first" },
      { step: 3, instruction: "Be prepared for strong retention offers" },
    ],
  },
  {
    name: "WSJ Digital",
    slug: "wsj-digital",
    category: "News",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 38.99,
    yearlyPrice: 467.88,
    difficultyScore: 4.0,
    darkPatternScore: 5.5,
    clicksToCancel: 0,
    estimatedCancelTime: 15,
    cancellationPhone: "1-800-568-7625",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Phone-only cancellation", "Retention offers"],
    alternatives: [{ name: "Apple News+", price: 12.99 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 1-800-568-7625" },
      { step: 2, instruction: "Request cancellation from the agent" },
      { step: 3, instruction: "Get confirmation number" },
    ],
  },
  {
    name: "The Economist",
    slug: "the-economist",
    category: "News",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 22.00,
    yearlyPrice: 189.00,
    difficultyScore: 3.5,
    darkPatternScore: 5.0,
    clicksToCancel: 0,
    estimatedCancelTime: 10,
    cancellationPhone: "1-800-456-6086",
    cancellationEmail: "customerservices@economist.com",
    cancellationMethod: "phone",
    freeTierAvailable: false,
    headquarters: "UK",
    darkPatterns: ["Phone/email only", "Retention offers"],
    alternatives: [{ name: "Apple News+", price: 12.99 }],
    cancellationSteps: [
      { step: 1, instruction: "Call 1-800-456-6086 or email customerservices@economist.com" },
      { step: 2, instruction: "Request cancellation" },
      { step: 3, instruction: "Navigate retention offers" },
    ],
  },

  // FOOD DELIVERY (6 companies)
  {
    name: "HelloFresh",
    slug: "hellofresh",
    category: "Food Delivery",
    regions: ["US", "UK", "EU", "AU", "CANADA"],
    avgMonthlyPrice: 51.93,
    yearlyPrice: 623.16,
    difficultyScore: 3.5,
    darkPatternScore: 5.5,
    clicksToCancel: 8,
    estimatedCancelTime: 10,
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "Germany",
    darkPatterns: ["Multiple retention screens", "Pause before cancel", "Confirmshaming", "Hidden cancel button"],
    alternatives: [{ name: "Cook at home", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Log in to hellofresh.com" },
      { step: 2, instruction: "Go to Account Settings > Plan Settings" },
      { step: 3, instruction: "Scroll down and click Cancel plan" },
      { step: 4, instruction: "Navigate through 5+ retention screens" },
    ],
  },
  {
    name: "DoorDash DashPass",
    slug: "doordash-dashpass",
    category: "Food Delivery",
    regions: ["US", "CANADA", "AU"],
    avgMonthlyPrice: 9.99,
    yearlyPrice: 96.00,
    difficultyScore: 1.8,
    darkPatternScore: 2.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Confirmshaming"],
    alternatives: [{ name: "No subscription", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open DoorDash app" },
      { step: 2, instruction: "Go to Account > Manage DashPass" },
      { step: 3, instruction: "Select Cancel DashPass" },
    ],
  },
  {
    name: "Uber One",
    slug: "uber-one",
    category: "Food Delivery",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 9.99,
    yearlyPrice: 96.00,
    difficultyScore: 1.8,
    darkPatternScore: 2.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Confirmshaming"],
    alternatives: [{ name: "No subscription", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open Uber app" },
      { step: 2, instruction: "Go to Account > Uber One" },
      { step: 3, instruction: "Click End membership" },
    ],
  },
  {
    name: "Instacart+",
    slug: "instacart-plus",
    category: "Food Delivery",
    regions: ["US", "CANADA"],
    avgMonthlyPrice: 9.99,
    yearlyPrice: 99.00,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Confirmshaming"],
    alternatives: [{ name: "No subscription", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open Instacart app or website" },
      { step: 2, instruction: "Go to Account > Instacart+ Membership" },
      { step: 3, instruction: "Select Cancel membership" },
    ],
  },
  {
    name: "Blue Apron",
    slug: "blue-apron",
    category: "Food Delivery",
    regions: ["US"],
    avgMonthlyPrice: 47.95,
    yearlyPrice: 575.40,
    difficultyScore: 3.0,
    darkPatternScore: 4.5,
    clicksToCancel: 6,
    estimatedCancelTime: 8,
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Retention screens", "Confirmshaming"],
    alternatives: [{ name: "Cook at home", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Log in to blueapron.com" },
      { step: 2, instruction: "Go to Account > Plan and Delivery" },
      { step: 3, instruction: "Select Cancel plan" },
    ],
  },

  // AI/TECH (5 companies)
  {
    name: "ChatGPT Plus",
    slug: "chatgpt-plus",
    category: "AI",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 20.00,
    yearlyPrice: 240.00,
    difficultyScore: 1.5,
    darkPatternScore: 1.0,
    clicksToCancel: 4,
    estimatedCancelTime: 2,
    cancellationUrl: "https://chat.openai.com/#settings/BillingSettings",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: [],
    alternatives: [{ name: "ChatGPT Free", price: 0 }, { name: "Claude Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to chat.openai.com > Settings > Subscription" },
      { step: 2, instruction: "Click Manage my subscription" },
      { step: 3, instruction: "Select Cancel plan" },
    ],
  },
  {
    name: "GitHub Copilot",
    slug: "github-copilot",
    category: "AI",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 10.00,
    yearlyPrice: 100.00,
    difficultyScore: 1.2,
    darkPatternScore: 0.5,
    clicksToCancel: 3,
    estimatedCancelTime: 2,
    cancellationUrl: "https://github.com/settings/billing",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: [],
    alternatives: [{ name: "Codeium Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to github.com > Settings > Billing" },
      { step: 2, instruction: "Under Copilot, click Cancel" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "Claude Pro",
    slug: "claude-pro",
    category: "AI",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 20.00,
    yearlyPrice: 240.00,
    difficultyScore: 1.5,
    darkPatternScore: 1.0,
    clicksToCancel: 3,
    estimatedCancelTime: 2,
    cancellationUrl: "https://claude.ai/settings",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: [],
    alternatives: [{ name: "Claude Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to claude.ai > Settings > Subscription" },
      { step: 2, instruction: "Click Cancel subscription" },
      { step: 3, instruction: "Confirm" },
    ],
  },

  // HEALTH/WELLNESS (6 companies)
  {
    name: "Headspace",
    slug: "headspace",
    category: "Health",
    regions: ["US", "UK", "EU", "AU", "GLOBAL"],
    avgMonthlyPrice: 12.99,
    yearlyPrice: 69.99,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationEmail: "help@headspace.com",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Insight Timer Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open the Headspace app" },
      { step: 2, instruction: "Go to Settings > Manage Subscription" },
      { step: 3, instruction: "Cancel through your app store" },
    ],
  },
  {
    name: "Calm",
    slug: "calm",
    category: "Health",
    regions: ["US", "UK", "EU", "AU", "GLOBAL"],
    avgMonthlyPrice: 14.99,
    yearlyPrice: 69.99,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationEmail: "help@calm.com",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Insight Timer Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Cancel through your app store subscription management" },
      { step: 2, instruction: "iPhone: Settings > Apple ID > Subscriptions > Calm" },
      { step: 3, instruction: "Android: Play Store > Payments > Calm" },
    ],
  },
  {
    name: "BetterHelp",
    slug: "betterhelp",
    category: "Health",
    regions: ["US", "UK", "AU"],
    avgMonthlyPrice: 65.00,
    yearlyPrice: 780.00,
    difficultyScore: 3.0,
    darkPatternScore: 4.0,
    clicksToCancel: 5,
    estimatedCancelTime: 5,
    cancellationEmail: "contact@betterhelp.com",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "7 Cups Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Log in to betterhelp.com" },
      { step: 2, instruction: "Go to Settings (gear icon)" },
      { step: 3, instruction: "Click Payment settings" },
      { step: 4, instruction: "Select Cancel membership" },
    ],
  },
  {
    name: "Weight Watchers",
    slug: "weight-watchers",
    category: "Health",
    regions: ["US", "UK", "AU", "GLOBAL"],
    avgMonthlyPrice: 22.95,
    yearlyPrice: 275.40,
    difficultyScore: 3.5,
    darkPatternScore: 5.0,
    clicksToCancel: 5,
    estimatedCancelTime: 8,
    cancellationPhone: "1-800-651-6000",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Retention offers", "Confirmshaming", "Early cancellation fees"],
    alternatives: [{ name: "MyFitnessPal Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Log in to weightwatchers.com" },
      { step: 2, instruction: "Go to Settings > Membership" },
      { step: 3, instruction: "Click Cancel membership" },
      { step: 4, instruction: "Or call 1-800-651-6000" },
    ],
  },

  // EDUCATION (6 companies)
  {
    name: "Duolingo Plus",
    slug: "duolingo-plus",
    category: "Education",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 12.99,
    yearlyPrice: 83.99,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers", "Streak guilt"],
    alternatives: [{ name: "Duolingo Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Cancel through your app store" },
      { step: 2, instruction: "iPhone: Settings > Apple ID > Subscriptions" },
      { step: 3, instruction: "Android: Play Store > Payments" },
    ],
  },
  {
    name: "Coursera Plus",
    slug: "coursera-plus",
    category: "Education",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 59.00,
    yearlyPrice: 399.00,
    difficultyScore: 2.5,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://www.coursera.org/my-purchases",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Coursera Free", price: 0 }, { name: "edX Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to coursera.org > My Purchases" },
      { step: 2, instruction: "Find your Coursera Plus subscription" },
      { step: 3, instruction: "Click Cancel and follow prompts" },
    ],
  },
  {
    name: "MasterClass",
    slug: "masterclass",
    category: "Education",
    regions: ["US", "UK", "EU", "AU", "GLOBAL"],
    avgMonthlyPrice: 10.00,
    yearlyPrice: 120.00,
    difficultyScore: 2.5,
    darkPatternScore: 3.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationEmail: "support@masterclass.com",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "YouTube tutorials", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to masterclass.com > Account Settings" },
      { step: 2, instruction: "Click Cancel Membership" },
      { step: 3, instruction: "Confirm" },
    ],
  },
  {
    name: "Skillshare",
    slug: "skillshare",
    category: "Education",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 13.99,
    yearlyPrice: 167.88,
    difficultyScore: 2.5,
    darkPatternScore: 3.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "YouTube tutorials", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to skillshare.com > Account Settings" },
      { step: 2, instruction: "Click Cancel Membership" },
      { step: 3, instruction: "Navigate retention screens" },
    ],
  },
  {
    name: "Scribd",
    slug: "scribd",
    category: "Education",
    regions: ["US", "UK", "EU", "GLOBAL"],
    avgMonthlyPrice: 11.99,
    yearlyPrice: 143.88,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://www.scribd.com/account-settings",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Libby (free with library card)", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to scribd.com/account-settings" },
      { step: 2, instruction: "Click Cancel your subscription" },
      { step: 3, instruction: "Confirm" },
    ],
  },

  // DATING (4 companies)
  {
    name: "Tinder Gold",
    slug: "tinder-gold",
    category: "Dating",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 29.99,
    yearlyPrice: 149.99,
    difficultyScore: 2.5,
    darkPatternScore: 4.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "Tinder Free", price: 0 }, { name: "Hinge Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Cancel through your app store" },
      { step: 2, instruction: "iPhone: Settings > Apple ID > Subscriptions > Tinder" },
      { step: 3, instruction: "Android: Play Store > Payments > Tinder" },
    ],
  },
  {
    name: "Bumble Premium",
    slug: "bumble-premium",
    category: "Dating",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 39.99,
    yearlyPrice: 229.99,
    difficultyScore: 2.5,
    darkPatternScore: 4.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Bumble Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Cancel through your app store" },
      { step: 2, instruction: "iPhone: Settings > Apple ID > Subscriptions > Bumble" },
      { step: 3, instruction: "Android: Play Store > Payments > Bumble" },
    ],
  },
  {
    name: "Hinge Preferred",
    slug: "hinge-preferred",
    category: "Dating",
    regions: ["US", "UK", "EU", "AU", "GLOBAL"],
    avgMonthlyPrice: 29.99,
    yearlyPrice: 179.99,
    difficultyScore: 2.5,
    darkPatternScore: 3.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Hinge Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Cancel through your app store" },
      { step: 2, instruction: "iPhone: Settings > Apple ID > Subscriptions > Hinge" },
      { step: 3, instruction: "Android: Play Store > Payments > Hinge" },
    ],
  },

  // GAMING (5 companies)
  {
    name: "Xbox Game Pass",
    slug: "xbox-game-pass",
    category: "Gaming",
    regions: ["US", "UK", "EU", "AU", "GLOBAL"],
    avgMonthlyPrice: 16.99,
    yearlyPrice: 203.88,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 5,
    estimatedCancelTime: 4,
    cancellationUrl: "https://account.microsoft.com/services",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "Free-to-play games", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to account.microsoft.com/services" },
      { step: 2, instruction: "Find Xbox Game Pass" },
      { step: 3, instruction: "Click Manage then Cancel" },
    ],
  },
  {
    name: "PlayStation Plus",
    slug: "playstation-plus",
    category: "Gaming",
    regions: ["US", "UK", "EU", "AU", "GLOBAL"],
    avgMonthlyPrice: 17.99,
    yearlyPrice: 79.99,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 5,
    estimatedCancelTime: 4,
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "Japan",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Free-to-play games", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to PlayStation Store > Account Settings" },
      { step: 2, instruction: "Select Subscription" },
      { step: 3, instruction: "Turn off Auto-Renew" },
    ],
  },
  {
    name: "Nintendo Switch Online",
    slug: "nintendo-switch-online",
    category: "Gaming",
    regions: ["US", "UK", "EU", "AU", "GLOBAL"],
    avgMonthlyPrice: 3.99,
    yearlyPrice: 19.99,
    difficultyScore: 1.5,
    darkPatternScore: 2.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "Japan",
    darkPatterns: [],
    alternatives: [{ name: "Offline gaming", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to Nintendo eShop" },
      { step: 2, instruction: "Select your profile > Nintendo Switch Online" },
      { step: 3, instruction: "Turn off Automatic Renewal" },
    ],
  },

  // CLOUD STORAGE (4 companies)
  {
    name: "iCloud+",
    slug: "icloud-plus",
    category: "Cloud Storage",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 2.99,
    yearlyPrice: 35.88,
    difficultyScore: 1.5,
    darkPatternScore: 1.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: [],
    alternatives: [{ name: "Google Drive Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "iPhone: Settings > Apple ID > iCloud > Manage Storage" },
      { step: 2, instruction: "Select Change Storage Plan" },
      { step: 3, instruction: "Downgrade to free 5GB" },
    ],
  },
  {
    name: "Google One",
    slug: "google-one",
    category: "Cloud Storage",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 2.99,
    yearlyPrice: 29.99,
    difficultyScore: 1.5,
    darkPatternScore: 1.5,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationUrl: "https://one.google.com/settings",
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "US",
    darkPatterns: [],
    alternatives: [{ name: "Google Drive Free 15GB", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to one.google.com/settings" },
      { step: 2, instruction: "Click Cancel membership" },
      { step: 3, instruction: "Confirm" },
    ],
  },

  // ENTERTAINMENT/MISC (5 companies)
  {
    name: "Audible",
    slug: "audible",
    category: "Entertainment",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 14.95,
    yearlyPrice: 149.50,
    difficultyScore: 3.5,
    darkPatternScore: 5.0,
    clicksToCancel: 5,
    estimatedCancelTime: 5,
    cancellationUrl: "https://www.audible.com/account/cancel",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Retention offers", "Pause option", "Confirmshaming"],
    alternatives: [{ name: "Libby (free with library card)", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Go to audible.com/account" },
      { step: 2, instruction: "Click Cancel membership at the bottom" },
      { step: 3, instruction: "Navigate through 3-4 retention offer screens" },
      { step: 4, instruction: "Confirm cancellation" },
    ],
  },
  {
    name: "Naver Webtoon",
    slug: "naver-webtoon",
    category: "Entertainment",
    regions: ["SOUTH_KOREA", "US", "GLOBAL"],
    avgMonthlyPrice: 6.99,
    yearlyPrice: 69.99,
    difficultyScore: 2.0,
    darkPatternScore: 3.0,
    clicksToCancel: 4,
    estimatedCancelTime: 3,
    cancellationMethod: "online",
    freeTierAvailable: true,
    headquarters: "South Korea",
    darkPatterns: ["Retention offers"],
    alternatives: [{ name: "Webtoon Free", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Open Webtoon app" },
      { step: 2, instruction: "Go to Settings > Subscription" },
      { step: 3, instruction: "Cancel through app store" },
    ],
  },
  {
    name: "Birchbox",
    slug: "birchbox",
    category: "Shopping",
    regions: ["US", "UK"],
    avgMonthlyPrice: 15.00,
    yearlyPrice: 180.00,
    difficultyScore: 3.0,
    darkPatternScore: 4.0,
    clicksToCancel: 5,
    estimatedCancelTime: 5,
    cancellationEmail: "info@birchbox.com",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Retention offers", "Confirmshaming"],
    alternatives: [{ name: "No subscription", price: 0 }],
    cancellationSteps: [
      { step: 1, instruction: "Log in to birchbox.com" },
      { step: 2, instruction: "Go to Account Settings" },
      { step: 3, instruction: "Click Cancel Subscription" },
    ],
  },
  {
    name: "Amazon Prime",
    slug: "amazon-prime",
    category: "Shopping",
    regions: ["US", "UK", "EU", "INDIA", "AU", "GLOBAL"],
    avgMonthlyPrice: 14.99,
    yearlyPrice: 139.00,
    difficultyScore: 3.5,
    darkPatternScore: 7.5,
    clicksToCancel: 6,
    estimatedCancelTime: 10,
    cancellationUrl: "https://www.amazon.com/mc/pipelines/cancel-prime",
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "US",
    darkPatterns: ["Confirmshaming", "Misdirection", "Obstruction", "Visual interference", "Roach motel"],
    alternatives: [{ name: "Walmart+", price: 12.95 }],
    knownLawsuits: "FTC lawsuit 2023 - Project Iliad dark pattern case",
    cancellationSteps: [
      { step: 1, instruction: "Go to amazon.com > Account > Prime Membership" },
      { step: 2, instruction: "Click 'End Membership'" },
      { step: 3, instruction: "Navigate through 6+ reminder screens about benefits" },
      { step: 4, instruction: "Choose end date" },
      { step: 5, instruction: "Confirm cancellation" },
    ],
  },

  // GERMANY-SPECIFIC
  {
    name: "Telekom Germany",
    slug: "telekom-germany",
    category: "Internet/Cable",
    regions: ["EU", "GERMANY"],
    avgMonthlyPrice: 39.95,
    yearlyPrice: 479.40,
    difficultyScore: 3.0,
    darkPatternScore: 4.0,
    clicksToCancel: 3,
    estimatedCancelTime: 5,
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "Germany",
    darkPatterns: ["Notice period"],
    alternatives: [{ name: "1&1", price: 30 }],
    cancellationSteps: [
      { step: 1, instruction: "Germany law requires a Kundigungsbutton (cancellation button)" },
      { step: 2, instruction: "Go to telekom.de > Mein Konto > Vertrag kundigen" },
      { step: 3, instruction: "Use the mandatory cancellation button" },
    ],
  },
  {
    name: "Vodafone Germany",
    slug: "vodafone-germany",
    category: "Internet/Cable",
    regions: ["EU", "GERMANY"],
    avgMonthlyPrice: 34.99,
    yearlyPrice: 419.88,
    difficultyScore: 3.0,
    darkPatternScore: 4.0,
    clicksToCancel: 3,
    estimatedCancelTime: 5,
    cancellationMethod: "online",
    freeTierAvailable: false,
    headquarters: "Germany",
    darkPatterns: ["Notice period"],
    alternatives: [{ name: "1&1", price: 30 }],
    cancellationSteps: [
      { step: 1, instruction: "Germany law requires a Kundigungsbutton (cancellation button)" },
      { step: 2, instruction: "Go to vodafone.de > Mein Konto > Vertrag kundigen" },
      { step: 3, instruction: "Use the mandatory cancellation button" },
    ],
  },
];

async function main() {
  console.log("Seeding database with " + companies.length + " companies...");

  for (const company of companies) {
    const companyData = {
      name: company.name,
      slug: company.slug,
      category: company.category,
      regions: company.regions || ["GLOBAL"],
      avgMonthlyPrice: company.avgMonthlyPrice,
      yearlyPrice: company.yearlyPrice,
      difficultyScore: company.difficultyScore,
      darkPatternScore: company.darkPatternScore,
      clicksToCancel: company.clicksToCancel || 3,
      estimatedCancelTime: company.estimatedCancelTime || 5,
      cancellationUrl: company.cancellationUrl || null,
      cancellationPhone: company.cancellationPhone || null,
      cancellationEmail: company.cancellationEmail || null,
      cancellationMethod: company.cancellationMethod || "online",
      cancellationSteps: company.cancellationSteps,
      freeTierAvailable: company.freeTierAvailable || false,
      headquarters: company.headquarters || null,
      darkPatterns: JSON.stringify(company.darkPatterns || []),
      alternatives: JSON.stringify(company.alternatives || []),
      knownLawsuits: company.knownLawsuits || null,
      totalCancellations: Math.floor(Math.random() * 50000) + 1000,
    };

    await prisma.saasCompany.upsert({
      where: { slug: company.slug },
      update: companyData,
      create: companyData,
    });
  }

  console.log("Seeded " + companies.length + " companies successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
