name = "grabtube-license"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "grabtube-licenses"
database_id = "7fab7a22-cd2d-4efc-ac08-574372dd7290"
